Repository lsst-it/lsst-control, pull requests merged in 2022-08, with the labels that each got.

#632 (tu site) bump k8s to v1.23.7-rancher1-1
  hieradata/site/tu/role/rke.yaml
Labels: author-merge, live-hosts

#634 Add FQDN entry to /etc/hosts on CCS clusters
  Puppetfile
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/pathfinder-ccs.yaml
Labels: ccs

#627 (foreman role) add foreman discovery plugin
  Puppetfile
  hieradata/role/foreman.yaml
  site/profile/files/foreman/udev_fact.zip
  site/profile/manifests/core/puppet_master.pp
  spec/classes/core/puppet_master_spec.rb
  spec/hosts/roles/foreman_spec.rb
  spec/spec_helper.rb
Labels: author-merge, live-hosts

#636 hiera: add ccs pathfinder and hexvalves services on comcam-lion03
  hieradata/node/comcam-lion03.cp.lsst.org.yaml
Labels: ccs

#637 update ccs related puppet mods for EL8 support
  Puppetfile
  hieradata/node/auxtel-fp01.cp.lsst.org.yaml
  hieradata/node/comcam-dc01.cp.lsst.org.yaml
  hieradata/role/atsccs.yaml
  hieradata/role/atsdaq.yaml
  hieradata/role/atshcu.yaml
  hieradata/role/ccs-dc.yaml
  hieradata/role/ccs-desktop.yaml
  hieradata/role/ccs-hcu.yaml
  hieradata/role/ccs-virt.yaml
  hieradata/role/ccs-viswork.yaml
  hieradata/role/comcam-fp.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
  site/profile/manifests/ccs/common.pp
  site/profile/manifests/ccs/facts.pp
  site/profile/manifests/ccs/monitoring.pp
Labels: author-merge

#639 puppet6 -> puppet7 migration
  Puppetfile
  hieradata/common.yaml
  hieradata/role/foreman.yaml
  hieradata/role/puppetdb.yaml
  site/profile/manifests/core/foreman_envsync.pp
  site/profile/manifests/core/puppet_master.pp
  spec/classes/core/foreman_envsync_spec.rb
  spec/default_facts.yml
  spec/hosts/roles/foreman_spec.rb
  spec/hosts/roles/puppetdb_spec.rb
Labels: depends-on-another-pr, author-merge, live-hosts

#641 (cp site) bump rke to 1.3.12
  hieradata/site/cp/role/rke.yaml
Labels: author-merge, live-hosts
