Repository lsst-it/lsst-control, pull requests merged in 2023-05, with the labels that each got.

#810 (ccs) bump DAQ version to R5-V6.1
  hieradata/role/atsdaq.yaml
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/cp/cluster/comcam-ccs.yaml
  hieradata/site/ls/cluster/auxtel-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
  hieradata/site/tu/role/atsdaq.yaml
Labels: enhancement, ccs

#811 (tu/cluster/auxtel-ccs) use ccs lockmanager
  hieradata/node/auxtel-mcm.tu.lsst.org.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
Labels: enhancement, ccs

#813 (ccs) deploy new auxtel and comcam ccs software releases
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#814 (profile::ccs::graphical) rm cockpit packages from `Server with GUI`
  site/profile/manifests/ccs/graphical.pp
  spec/classes/ccs/graphical_spec.rb
Labels: bug

#815 (profile::core::remote_desktop) rm class -- unused
  site/profile/manifests/core/remote_desktop.pp
Labels: bug

#817 (ccs) use lockmanager on summit auxtel hosts
  hieradata/node/auxtel-mcm.cp.lsst.org.yaml
  hieradata/site/cp/cluster/auxtel-ccs.yaml
Labels: enhancement, ccs

#818 (ccs) use lockmanager on all auxtel hosts
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/node/auxtel-mcm.ls.lsst.org.yaml
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
Labels: enhancement, ccs

#821 (node/auxtel-archiver.{tu,cp}.lsst.org) rm /data/allsky nfs export
  hieradata/node/auxtel-archiver.cp.lsst.org.yaml
  hieradata/node/auxtel-archiver.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-archiver.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-archiver.tu.lsst.org_spec.rb
Labels: bug

#820 (node/auxtel-{archiver,dc01,fp01,mcm}.ls.lsst.org) fix nfs exports
  hieradata/node/auxtel-archiver.ls.lsst.org.yaml
  hieradata/node/auxtel-dc01.ls.lsst.org.yaml
  hieradata/node/auxtel-fp01.ls.lsst.org.yaml
  hieradata/node/auxtel-mcm.ls.lsst.org.yaml
  spec/hosts/nodes/auxtel-archiver.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-fp01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-mcm.ls.lsst.org_spec.rb
Labels: bug

#824 (spec) always skip testing on el7 instead of pinning tests to el8
  spec/hosts/nodes/auxtel-archiver.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-fp01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-mcm.ls.lsst.org_spec.rb
  spec/hosts/nodes/azar01.ls.lsst.org_spec.rb
  spec/hosts/nodes/dimm.cp.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.ls.lsst.org_spec.rb
  spec/hosts/nodes/love01.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-archiver.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-daq-mgt.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-db01.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-mcm.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/tel-hw1.ls.lsst.org_spec.rb
Labels: enhancement

#825 (profile::core::docker) bump docker-ce to 23.0.6
  Puppetfile
  hieradata/role/amor.yaml
  hieradata/role/dco.yaml
  hieradata/role/docker-compose.yaml
  hieradata/role/hexrot.yaml
  hieradata/role/ts-csc.yaml
  site/profile/data/common.yaml
  site/profile/data/osfamily/RedHat/major/7.yaml
  site/profile/data/osfamily/RedHat/major/8.yaml
  site/profile/data/osfamily/RedHat/major/9.yaml
  site/profile/manifests/core/docker.pp
  site/profile/manifests/core/docker/compose.pp
  spec/classes/core/docker/compose_spec.rb
  spec/classes/core/docker_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#828 (profile::ccs::common) add time package
  site/profile/data/common.yaml
  site/profile/manifests/ccs/common.pp
  spec/classes/ccs/common_spec.rb
  spec/hosts/roles/atsccs_spec.rb
  spec/hosts/roles/atsdaq_spec.rb
  spec/hosts/roles/atshcu_spec.rb
  spec/hosts/roles/ccs_dc_spec.rb
  spec/hosts/roles/ccs_desktop_spec.rb
  spec/hosts/roles/ccs_hcu_spec.rb
  spec/hosts/roles/ccs_mcm_spec.rb
  spec/hosts/roles/ccs_viswork_spec.rb
  spec/spec_helper.rb
Labels: enhancement, ccs

#829 (!site/cp) set docker::log_opt log size limits
  hieradata/common.yaml
  hieradata/site/cp.yaml
  spec/spec_helper.rb
Labels: enhancement, live-hosts

#830 (node/azar03.cp) Add network config for EL8
  hieradata/node/azar03.cp.lsst.org.yaml
  spec/hosts/nodes/azar03.cp.lsst.org_spec.rb
Labels: enhancement

#827 (core{01-03}.dev) Network Config and Tests
  hieradata/node/core01.dev.lsst.org.yaml
  hieradata/node/core02.dev.lsst.org.yaml
  hieradata/node/core03.dev.lsst.org.yaml
  spec/hosts/nodes/core01.dev.lsst.org_spec.rb
  spec/hosts/nodes/core02.dev.lsst.org_spec.rb
  spec/hosts/nodes/core03.dev.lsst.org_spec.rb
Labels: enhancement

#831 (core/common) add packages and tests
  site/profile/data/common.yaml
  spec/classes/core/convenience_spec.rb
Labels: enhancement

#832 (node/*) rm iip user for .k5login; keytab for iip user already removed
  hieradata/node/auxtel-archiver.cp.lsst.org.yaml
  hieradata/node/auxtel-archiver.tu.lsst.org.yaml
  hieradata/node/comcam-archiver.cp.lsst.org.yaml
  hieradata/node/comcam-archiver.tu.lsst.org.yaml
Labels: bug

#833 (node/tel-hw1.ls.lsst.org) add /net/obs-env nfs mount
  hieradata/node/tel-hw1.ls.lsst.org.yaml
  spec/hosts/nodes/tel-hw1.ls.lsst.org_spec.rb
Labels: enhancement, live-hosts
