Repository lsst-it/lsst-control, pull requests merged in 2023-08, with the labels that each got.

#881 (profile::core::x2go) add support for EL9
  hieradata/common/osfamily/RedHat/major/9.yaml
  site/profile/data/common.yaml
  site/profile/data/osfamily/RedHat/major/9.yaml
  site/profile/manifests/core/x2go.pp
  spec/classes/core/x2go_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#883 (node/netdev.dev) rm; host does not exist
  hieradata/node/netdev.dev.lsst.org.yaml
Labels: bug

#886 (Puppetfile) bump simp/auditd to update deps
  Puppetfile
Labels: enhancement

#885 (ccs) new software release for auxtel and comcam clusters
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#887 (*) RIP icinga
  Puppetfile
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/common.yaml
  hieradata/common/osfamily/RedHat/major/9.yaml
  hieradata/node/allsky2-cam.cp.lsst.org.yaml
  hieradata/role/dnscache.yaml
  hieradata/role/dtn.yaml
  hieradata/role/icinga-master.yaml
  hieradata/role/ipareplica.yaml
  hieradata/site/cp.yaml
  hieradata/site/cp/role/foreman.yaml
  hieradata/site/cp/role/icinga-master.yaml
  hieradata/site/cp/role/rpi.yaml
  hieradata/site/dev.yaml
  hieradata/site/dev/role/icinga-master.yaml
  hieradata/site/dmz.yaml
  hieradata/site/ls.yaml
  hieradata/site/ls/role/foreman.yaml
  hieradata/site/ls/role/icinga-master.yaml
  hieradata/site/ls/role/rpi.yaml
  hieradata/site/tu.yaml
  hieradata/site/tu/role/icinga-master.yaml
  site/profile/manifests/core/common.pp
  site/profile/manifests/icinga/agent.pp
  site/profile/manifests/icinga/master.pp
  site/profile/manifests/icinga/network.pp
  site/profile/manifests/icinga/opsgenie.pp
  site/profile/manifests/icinga/plugins.pp
  site/profile/manifests/icinga/resources.pp
  spec/classes/icinga/master_spec.rb
  spec/classes/icinga/plugins_spec.rb
  spec/fixtures/hieradata/common.yaml
  spec/hosts/roles/icinga_master_spec.rb
Labels: enhancement

#890 (site/cp/role/foreman) change vlan1101 dhcp pool to 139.229.160.115-126
  hieradata/site/cp/role/foreman.yaml
  spec/hosts/roles/foreman_spec.rb
Labels: bug

#844 (core{01-03}.dev) Network Config / Variant / Tests
  hieradata/site/dev/variant/1114S-rev_1.01.yaml
  spec/hosts/nodes/core01.dev.lsst.org_spec.rb
  spec/hosts/nodes/core02.dev.lsst.org_spec.rb
  spec/hosts/nodes/core03.dev.lsst.org_spec.rb
Labels: enhancement

#888 (*) migrate from bodgit/sssd -> puppet/sssd
  Puppetfile
  hieradata/common.yaml
  hieradata/common/osfamily/RedHat/major/7.yaml
  hieradata/site/cp.yaml
  hieradata/site/dev.yaml
  hieradata/site/dmz.yaml
  hieradata/site/ls.yaml
  site/profile/manifests/core/common.pp
  spec/classes/core/ipa_pwd_reset_spec.rb
  spec/classes/core/ipa_spec.rb
  spec/classes/core/krb5_spec.rb
  spec/classes/core/rke_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#894 (Puppetfile) bump simp/auditd to allow updated deps
  Puppetfile
Labels: enhancement

#884 (role/ipareplica) add tailscale vpn to work around noirlab firewall
  Puppetfile
  hieradata/role/ipareplica.yaml
  spec/fixtures/hieradata/common.yaml
  spec/hosts/roles/ipareplica_spec.rb
Labels: enhancement

#896 (ccs) tidy up daqsdk version setting
  hieradata/cluster/comcam-ccs.yaml
  hieradata/site/cp/cluster/comcam-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#897 (foreman.cp) Fix range on LHN summit network
  hieradata/site/cp/role/foreman.yaml
  spec/hosts/roles/foreman_spec.rb
Labels: bug

#880 (ccs) install file-transfer utilities
  hieradata/role/atsdaq.yaml
  hieradata/role/comcam-fp.yaml
  hieradata/site/ls/role/ccs-dc.yaml
  site/profile/data/common.yaml
  site/profile/manifests/ccs/common.pp
  site/profile/manifests/ccs/file_transfer.pp
  spec/classes/ccs/file_transfer_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/hosts/roles/comcam_fp_spec.rb
Labels: enhancement, ccs

#898 (ccs) update ts_sal_utils for cycle 32
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/cp/cluster/comcam-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#899 (cluster/comcam-ccs) no longer install old ccs software versions
  hieradata/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#882 (common) rm /etc/rc.d/rc.local on EL*
  hiera.yaml
  hieradata/common/osfamily/RedHat.yaml
  spec/fixtures/hiera.yaml
  spec/spec_helper.rb
Labels: enhancement
