Repository lsst-it/lsst-control, pull requests merged in 2023-03, with the labels that each got.

#750 (site/ls/role/foreman) rm 139.229.152/25 gw (dhcp routers option)
  hieradata/site/ls/role/foreman.yaml
  spec/hosts/roles/foreman_spec.rb
Labels: bug, author-merge, live-hosts

#751 (manke) fix lhn ip rule
  hieradata/cluster/manke.yaml
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
Labels: bug, live-hosts

#754 (role/foreman) retire {dev,tu,ls}_production env name
  hieradata/site/dev/role/foreman.yaml
  hieradata/site/ls/role/foreman.yaml
  hieradata/site/tu/role/foreman.yaml
  spec/hosts/roles/foreman_spec.rb
Labels: enhancement, depends-on-another-pr

#755 (gha) add require pr labels workflow
  .github/workflows/pr_labels.yaml
Labels: enhancement

#756 (gha) add commit message checker workflow
  .github/workflows/commit_messages.yaml
  .overcommit.yml
Labels: enhancement

#757 (gha) add block merge commits workflow
  .github/workflows/block_merge_commits.yaml
Labels: enhancement

#759 (dimm.cp) add network config and tests
  hieradata/node/dimm.cp.lsst.org.yaml
  spec/hosts/nodes/dimm.cp.lsst.org_spec.rb
Labels: enhancement

#761 Small CCS tweaks related to RHEL 8
  Puppetfile
  site/profile/manifests/ccs/graphical.pp
Labels: enhancement, ccs

#762 (auxtel-mcm.ls) add ccs software global parameters and services tests
  spec/hosts/nodes/auxtel-mcm.ls.lsst.org_spec.rb
Labels: enhancement, ccs

#763 (cluster/lsscam-ccs) add ccs software version 1.0.1
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#765 (konkong) initial network config and test
  hieradata/cluster/konkong.yaml
  hieradata/cluster/konkong/role/rke.yaml
  spec/hosts/nodes/konkong01.lsst.org_spec.rb
Labels: enhancement

#766 (role/foreman) migrate foreman_envsync hub.docker.com -> ghcr.io
  Puppetfile
  hieradata/role/foreman.yaml
  spec/spec_helper.rb
Labels: enhancement

#768 (role/dco) Add obs-env mount at Summit azar nodes
  hieradata/site/cp/role/dco.yaml
  spec/hosts/roles/dco_spec.rb
Labels: enhancement

#770 (role/ccs-dc) add ccs_daq module
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/role/ccs-dc.yaml
  spec/hosts/roles/ccs_dc_spec.rb
Labels: enhancement, ccs

#771 (role/foreman) fix foreman_envsync tag name
  hieradata/role/foreman.yaml
  spec/spec_helper.rb
Labels: bug

#774 (node/tel-hw1.tu) add obs-env nfs mount
  hieradata/node/tel-hw1.tu.lsst.org.yaml
  spec/hosts/nodes/tel-hw1.tu.lsst.org_spec.rb
Labels: enhancement

#775 (role/nfsserver.cp) export to startracker network
  hieradata/site/cp/role/nfsserver.yaml
Labels: enhancement

#772 (dimm.cp) add ts_dimm_app package
  hieradata/role/dimm.yaml
  spec/hosts/roles/dimm_spec.rb
Labels: enhancement

#777 (kueyen) Add support config for EL8
  hieradata/cluster/kueyen.yaml
  hieradata/cluster/kueyen/role/rke.yaml
  spec/hosts/nodes/kueyen01.ls.lsst.org_spec.rb
Labels: enhancement

#776 (hiera) fix yamllint warnings
  .yamllint.yaml
  hieradata/cluster/kueyen.yaml
  hieradata/node/dimm.cp.lsst.org.yaml
  hieradata/node/perfsonar1.ls.lsst.org.yaml
Labels: bug
