Repository lsst-it/lsst-control, pull requests merged in 2023-09, with the labels that each got.

#902 (site/cp/role/foremean) change vlan1511 dhcp pool to 139.229.175.101-120
  hieradata/site/cp/role/foreman.yaml
  spec/hosts/roles/foreman_spec.rb
Labels: bug

#906 (role/ipareplica) update ipa[12].dev tailscale addresses
  hieradata/role/ipareplica.yaml
  spec/hosts/roles/ipareplica_spec.rb
Labels: enhancement

#892 (role/nfsserver.cp) add nfs2 to jhome client list
  hieradata/site/cp/role/nfsserver.yaml
  spec/hosts/roles/nfsserver_spec.rb
Labels: enhancement

#910 (ccs) make java17 the default for tu/comcam
  Puppetfile
  hieradata/site/tu/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#911 (role/ipareplica) update ipa[123].ls tailscale addresses
  hieradata/role/ipareplica.yaml
  spec/hosts/roles/ipareplica_spec.rb
Labels: enhancement

#901 (Puppetfile) bump misc. modules to allow stdlib 9.x
  Puppetfile
Labels: enhancement

#903 (Puppetfile) patch theforeman/foreman* to allow stdlib 9.x
  Puppetfile
Labels: enhancement

#912 (profile::ccs::jdk11) rm; unused
  site/profile/manifests/ccs/jdk11.pp
  site/profile/templates/ccs/jdk11/ccs-console.epp
  site/profile/templates/ccs/jdk11/jdk11.epp
Labels: enhancement

#913 (rke) add restic backup to rke role.
  Puppetfile
  hieradata/role/rke.yaml
  spec/fixtures/hieradata/common.yaml
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#914 (rke) add etc to backup
  hieradata/role/rke.yaml
Labels: enhancement

#905 (ccs) allow installation of required jdk8 on el9
  site/profile/manifests/ccs/common.pp
  site/profile/manifests/ccs/el9.pp
  spec/classes/ccs/el9_spec.rb
Labels: enhancement, ccs

#907 (yagan) add EL9 network support and test
  hieradata/cluster/yagan/osfamily/RedHat/major/9.yaml
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
Labels: enhancement

#915 (cluster/yagan) add yagan11-20
  hieradata/cluster/yagan.yaml
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
Labels: enhancement

#916 (cluster/yagan) migrate yagan01-10 to EL9
  hiera.yaml
  hieradata/cluster/yagan.yaml
  hieradata/cluster/yagan/variant/1114s.yaml
  hieradata/cluster/yagan/variant/1114s/subvariant/1.01.yaml
  hieradata/cluster/yagan/variant/1114s/subvariant/1.02.yaml
  hieradata/node/yagan01.cp.lsst.org.yaml
  hieradata/node/yagan02.cp.lsst.org.yaml
  hieradata/node/yagan03.cp.lsst.org.yaml
  hieradata/node/yagan04.cp.lsst.org.yaml
  hieradata/node/yagan05.cp.lsst.org.yaml
  hieradata/node/yagan06.cp.lsst.org.yaml
  hieradata/node/yagan07.cp.lsst.org.yaml
  spec/fixtures/hiera.yaml
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
Labels: enhancement

#917 (cluster/lukay) fwv
  hieradata/cluster/lukay.yaml
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
Labels: enhancement

#918 (cluster/yepun) migrate cluster to EL9
  hieradata/cluster/yepun.yaml
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
Labels: enhancement

#919 (cluster/chonchon) migrate to EL9
  hieradata/cluster/chonchon.yaml
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
Labels: enhancement

#920 (cluster/ruka) rm EL7 network support
  hieradata/cluster/ruka/osfamily/RedHat/major/7.yaml
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka04.dev.lsst.org_spec.rb
Labels: enhancement

#922 (profile::core::hardware) include profile::core::powertop
  hieradata/cluster/ayekan.yaml
  hieradata/cluster/chonchon.yaml
  hieradata/cluster/konkong.yaml
  hieradata/cluster/kueyen.yaml
  hieradata/cluster/luan.yaml
  hieradata/cluster/manke.yaml
  hieradata/cluster/namkueyen.yaml
  hieradata/cluster/pillan.yaml
  hieradata/cluster/rancher.yaml
  hieradata/cluster/ruka.yaml
  hieradata/cluster/yagan.yaml
  hieradata/cluster/yepun.yaml
  hieradata/site/tu.yaml
  site/profile/manifests/core/common.pp
  site/profile/manifests/core/hardware.pp
  spec/spec_helper.rb
Labels: enhancement

#923 (role/ipareplica) bump el7 ipa to 4.6.8-5.el7.centos.14
  hieradata/role/ipareplica.yaml
  hieradata/role/ipareplica/osfamily/RedHat/major/7.yaml
  spec/hosts/roles/ipareplica_spec.rb
Labels: enhancement

#924 (role/ipareplica) update tailscale address for ipa3.tu.lsst.org
  hieradata/role/ipareplica.yaml
  spec/hosts/roles/ipareplica_spec.rb
Labels: enhancement

#925 (role/ipareplica) update tailscale address for ipa1.tu.lsst.org
  hieradata/role/ipareplica.yaml
  spec/hosts/roles/ipareplica_spec.rb
Labels: enhancement

#927 (node/tel-lt1.tu.lsst.org) rm -- retired
  hieradata/node/tel-hw1.tu.lsst.org.yaml
  hieradata/node/tel-lt1.tu.lsst.org.yaml
  spec/hosts/nodes/tel-hw1.tu.lsst.org_spec.rb
  spec/hosts/nodes/tel-lt1.tu.lsst.org_spec.rb
Labels: enhancement

#932 (site/cp/role/foreman) add IT-CORE-SERVICES|IT-HYPERVISOR|IT-BMC pools
  hieradata/site/cp/role/foreman.yaml
  spec/hosts/roles/foreman_spec.rb
Labels: enhancement

#929 (node/core0[123].cp.lsst.org) add 1114s based servers
  hieradata/node/core01.cp.lsst.org.yaml
  hieradata/node/core02.cp.lsst.org.yaml
  hieradata/node/core03.cp.lsst.org.yaml
  hieradata/site/cp/role/hypervisor.yaml
  spec/hosts/nodes/core01.cp.lsst.org_spec.rb
  spec/hosts/nodes/core02.cp.lsst.org_spec.rb
  spec/hosts/nodes/core03.cp.lsst.org_spec.rb
Labels: enhancement

#926 (node/core[123].tu.lsst.org) migrate to EL9
  hieradata/common.yaml
  hieradata/node/core1.tu.lsst.org.yaml
  hieradata/node/core2.tu.lsst.org.yaml
  hieradata/node/core3.tu.lsst.org.yaml
  hieradata/node/ipa1.tu.lsst.org.yaml
  hieradata/role/foreman.yaml
  hieradata/role/ipareplica.yaml
  hieradata/site/tu/role/hypervisor.yaml
  site/profile/data/common.yaml
  spec/hosts/nodes/core1.tu.lsst.org_spec.rb
  spec/hosts/nodes/core2.tu.lsst.org_spec.rb
  spec/hosts/nodes/core3.tu.lsst.org_spec.rb
  spec/hosts/roles/ipareplica_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#931 (node/net-dx.cp.lsst.org) rm -- retired
  hieradata/node/net-dx.cp.lsst.org.yaml
  hieradata/role/foreman.yaml
  hieradata/role/net-dx.yaml
  hieradata/role/sal-dx.yaml
  site/profile/manifests/core/net_dx.pp
  spec/hosts/roles/net_dx_spec.rb
  spec/hosts/roles/sal_dx_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#933 (role/hypervisor) fix libvirt startup on EL9
  Puppetfile
  hieradata/role/hypervisor/osfamily/RedHat/major/9.yaml
  spec/hosts/roles/hypervisor_spec.rb
Labels: enhancement

#934 (role/foreman) install fog-libvirt gem fork to enable q35 support required by EL9
  hieradata/common.yaml
  hieradata/role/foreman.yaml
  hieradata/site/cp/role/foreman.yaml
  hieradata/site/dev/role/foreman.yaml
  hieradata/site/ls/role/foreman.yaml
  hieradata/site/tu/role/foreman.yaml
  site/profile/manifests/core/foreman.pp
  site/profile/manifests/core/foreman/fog_hack.pp
  spec/classes/core/foreman/fog_hack_spec.rb
  spec/classes/core/foreman_spec.rb
  spec/spec_helper.rb
Labels: enhancement, live-hosts

#935 (cluster/rancher) rm network config -- default is dhcp
  hieradata/cluster/rancher.yaml
  spec/hosts/nodes/rancher01.dev.lsst.org_spec.rb
Labels: enhancement
