Repository lsst-it/lsst-control, pull requests merged in 2023-11, with the labels that each got.

#964 (node/foreman.*) migrate dhcp pool configuration from site/role -> node layer(s)
  hieradata/node/foreman.cp.lsst.org.yaml
  hieradata/node/foreman.dev.lsst.org.yaml
  hieradata/node/foreman.ls.lsst.org.yaml
  hieradata/node/foreman.tuc.lsst.cloud.yaml
  hieradata/role/foreman.yaml
  hieradata/site/cp/role/foreman.yaml
  hieradata/site/dev/role/foreman.yaml
  hieradata/site/ls/role/foreman.yaml
  hieradata/site/tu/role/foreman.yaml
  site/profile/manifests/core/dhcp.pp
  spec/hosts/nodes/foreman.cp.lsst.org_spec.rb
  spec/hosts/nodes/foreman.dev.lsst.org_spec.rb
  spec/hosts/nodes/foreman.ls.lsst.org_spec.rb
  spec/hosts/nodes/foreman.tuc.lsst.cloud_spec.rb
  spec/hosts/roles/foreman_spec.rb
  spec/spec_helper.rb
  spec/support/spec/dhcp.rb
Labels: enhancement

#965 (common) send telegraf metrics to mimir dev instance
  hieradata/common.yaml
  hieradata/site/cp.yaml
  hieradata/site/dev.yaml
  hieradata/site/dmz.yaml
  hieradata/site/ls.yaml
  hieradata/site/tu.yaml
  site/profile/manifests/core/common.pp
  site/profile/manifests/core/monitoring.pp
  spec/spec_helper.rb
  spec/support/spec/telegraf.rb
Labels: enhancement

#967 (role/puppetdb) bump puppetdb to 7.14.0
  hieradata/role/puppetdb.yaml
  spec/hosts/roles/puppetdb_spec.rb
Labels: enhancement

#946 (common) add backup credentials
  hieradata/common.yaml
  spec/spec_helper.rb
Labels: enhancement

#969 (role/foreman) enable puppet storeconfigs / send full reports to puppetdb
  hieradata/role/foreman.yaml
  hieradata/role/foreman/osfamily/RedHat/major/7.yaml
  hieradata/role/foreman/osfamily/RedHat/major/8.yaml
  spec/spec_helper.rb
Labels: enhancement

#968 (role/puppetdb) drop support for EL7 & EL8
  hieradata/role/puppetdb/osfamily/RedHat/major/7.yaml
  hieradata/role/puppetdb/osfamily/RedHat/major/8.yaml
  spec/hosts/roles/puppetdb_spec.rb
Labels: enhancement

#971 (hiera) use %{facts.os.*} instead of %{os.*}
  hiera.yaml
  spec/fixtures/hiera.yaml
Labels: bug

#970 (profile::core::hard) manage bmc on SSG-640SP-E1CR90
  site/profile/manifests/core/hardware.pp
  spec/classes/core/hardware_spec.rb
  spec/hosts/nodes/chango01.ls.lsst.org_spec.rb
Labels: bug

#972 (*) Capitalize bare words used to ref class names
  hieradata/role/perfsonar.yaml
  site/profile/manifests/ccs/postfix.pp
  site/profile/manifests/core/common.pp
  site/profile/manifests/core/ipa.pp
  site/profile/manifests/core/krb5.pp
  site/profile/manifests/core/nm_dispatch.pp
  site/profile/manifests/core/rke.pp
  site/profile/manifests/core/sssd.pp
Labels: bug

#973 (site/*) dedup rsyslog config; rm collector.lsst.org
  hieradata/common.yaml
  hieradata/site/cp.yaml
  hieradata/site/dev.yaml
  hieradata/site/dmz.yaml
  hieradata/site/ls.yaml
  hieradata/site/tu.yaml
  spec/spec_helper.rb
  spec/support/spec/rsyslog.rb
Labels: enhancement

#977 (node/auxtel-control01) remove network config
  hieradata/node/auxtel-control-01.cp.lsst.org.yaml
Labels: enhancement

#974 (common) setup default firewall rules
  hieradata/common.yaml
  hieradata/role/perfsonar.yaml
  hieradata/site/dev.yaml
  hieradata/site/ls.yaml
  site/profile/manifests/core/firewall.pp
  site/profile/manifests/core/ipset.pp
  spec/classes/core/firewall_spec.rb
  spec/hosts/roles/perfsonar_spec.rb
  spec/support/spec/firewall.rb
  spec/support/spec/ipset.rb
Labels: enhancement

#978 (common) prepare to use restic in multiple roles
  hieradata/common.yaml
  hieradata/role/foreman.yaml
  hieradata/role/rke.yaml
  spec/hosts/roles/rke_spec.rb
  spec/spec_helper.rb
  spec/support/spec/restic.rb
Labels: enhancement

#976 (common) purge telegraf config fragments; disable ethtool plugin
  hieradata/common.yaml
  spec/support/spec/telegraf.rb
Labels: enhancement

#980 (profile::core::ipa_pwd_reset) rm; no known users; will not work on el9
  hieradata/role/ipareplica.yaml
  site/profile/manifests/core/ipa_pwd_reset.pp
  spec/classes/core/ipa_pwd_reset_spec.rb
  spec/fixtures/hieradata/common.yaml
Labels: enhancement

#979 (auxtel-hcu02.cp) Summit Deployment
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/node/auxtel-hcu02.cp.lsst.org.yaml
  spec/hosts/nodes/auxtel-hcu02.cp.lsst.org_spec.rb
Labels: enhancement

#981 (role/atshcu) bump imanager version
  hieradata/role/atshcu.yaml
Labels: enhancement, ccs

#983 (role/ipareplica) update ipa1.tu tailscale address
  hieradata/role/ipareplica.yaml
  spec/hosts/roles/ipareplica_spec.rb
Labels: bug

#986 (role/rpi) add profile::core::docker
  hieradata/role/rpi.yaml
Labels: bug

#985 (Puppetfile) bump lsst/daq to 2.3.0
  Puppetfile
Labels: enhancement

#982 (profile::core::gpio) fwv
  hieradata/role/atshcu.yaml
  hieradata/role/rpi.yaml
  site/profile/data/common.yaml
  site/profile/manifests/core/gpio.pp
  spec/classes/core/gpio_spec.rb
  spec/hosts/roles/atshcu_spec.rb
  spec/hosts/roles/rpi_spec.rb
  spec/support/spec/gpio.rb
Labels: enhancement

#990 (profile::ts::rpi) rm docker package management -- not needed
  site/profile/manifests/ts/rpi.pp
  spec/classes/ts/rpi_spec.rb
Labels: bug

#989 (role/ess) rename role/rpi -> role/ess
  hieradata/role/ess.yaml
  spec/hosts/roles/ess_spec.rb
Labels: enhancement

#991 (profile::pi::config) fwv -- manages /boot/config.txt
  hieradata/common.yaml
  site/profile/manifests/pi/config.pp
  site/profile/manifests/pi/config/fragment.pp
  spec/classes/pi/config_spec.rb
  spec/defines/pi/config/fragment_spec.rb
Labels: enhancement

#987 (profile::core::i2c) fwv
  hieradata/role/ess.yaml
  site/profile/data/common.yaml
  site/profile/manifests/core/i2c.pp
  site/profile/manifests/pi/config/fragment.pp
  spec/classes/core/i2c_spec.rb
  spec/hosts/roles/ess_spec.rb
  spec/support/spec/i2c.rb
Labels: enhancement

#993 (role/{ess,lasterrpi}) rm profile::ts::rpi
  hieradata/role/ess.yaml
  hieradata/role/laserrpi.yaml
Labels: enhancement

#994 (role/allsky-cam) install libgphoto2 package
  hieradata/role/allsky-cam.yaml
  spec/hosts/roles/allsky_cam_spec.rb
Labels: enhancement

#995 (profile::pi::rubinhat) fwv
  hieradata/common.yaml
  hieradata/role/ess.yaml
  hieradata/role/laserrpi.yaml
  site/profile/manifests/pi/rubinhat.pp
  spec/classes/pi/rubinhat_spec.rb
  spec/hosts/roles/allsky_cam_spec.rb
  spec/hosts/roles/ess_spec.rb
  spec/hosts/roles/laserrpi_spec.rb
  spec/support/spec/rubinhat.rb
Labels: enhancement

#999 (common) bump puppet agent/server to 7.27.0/7.14.0
  hieradata/common.yaml
  hieradata/role/foreman.yaml
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: enhancement

#1000 (profile::core::gpio) restrict libgpiod-utils to el9
  site/profile/data/common.yaml
  site/profile/data/osfamily/RedHat/major/9.yaml
  spec/classes/core/gpio_spec.rb
  spec/hosts/roles/atshcu_spec.rb
  spec/hosts/roles/ess_spec.rb
  spec/support/spec/gpio.rb
Labels: bug

#1002 (trewa0[123].cp) remove trewa entries
  hieradata/node/trewa01.cp.lsst.org.yaml
  hieradata/node/trewa02.cp.lsst.org.yaml
  hieradata/node/trewa03.cp.lsst.org.yaml
  hieradata/role/ts-csc.yaml
  spec/hosts/roles/ts_csc_spec.rb
Labels: enhancement

#1003 (common) pin el7/aarch64 to puppet agent 7.24.0
  hiera.yaml
  hieradata/common/architecture/aarch64/osfamily/RedHat/major/7.yaml
  spec/fixtures/hiera.yaml
  spec/spec_helper.rb
Labels: bug

#1005 (role/ess) rm profile::core::{i2c,gpio} -- unused
  hieradata/role/ess.yaml
  spec/hosts/roles/ess_spec.rb
Labels: bug

#1004 (role/{ess,laserrpi}) rm uneeded docker keys
  hieradata/role/ess.yaml
  hieradata/role/laserrpi.yaml
Labels: bug

#1009 (spec) fix spec failures seen under gha
  spec/classes/core/foreman_spec.rb
Labels: bug

#1007 (ccs) add ccs releases for XML 21
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1008 (*) replace profile::pi::config with pi::config
  Puppetfile
  hieradata/common.yaml
  hieradata/role/ess.yaml
  site/profile/manifests/core/i2c.pp
  site/profile/manifests/pi/config.pp
  site/profile/manifests/pi/config/fragment.pp
  site/profile/manifests/pi/rubinhat.pp
  spec/classes/pi/config_spec.rb
  spec/defines/pi/config/fragment_spec.rb
  spec/support/spec/i2c.rb
  spec/support/spec/rubinhat.rb
Labels: enhancement

#997 (profile::pi::gpshat) fwv
  hieradata/role/laserrpi.yaml
  site/profile/data/common.yaml
  site/profile/manifests/pi/gpsd.pp
  site/profile/manifests/pi/gpshat.pp
  site/profile/manifests/pi/pigpio.pp
  spec/classes/pi/gpsd_spec.rb
  spec/classes/pi/gpshat_spec.rb
  spec/classes/pi/pigpio_spec.rb
  spec/hosts/roles/laserrpi_spec.rb
  spec/support/spec/gpsd.rb
  spec/support/spec/gpshat.rb
  spec/support/spec/pigpio.rb
Labels: enhancement

#1011 (role/ipareplica) update ipa1.ls tailscale address
  hieradata/node/ipa1.ls.lsst.org.yaml
  hieradata/role/ipareplica.yaml
  spec/hosts/roles/ipareplica_spec.rb
Labels: enhancement

#1006 (OCS-APP/Cleanup) OCS-APP DHCP removal and cleanup
  hieradata/node/foreman.cp.lsst.org.yaml
  spec/hosts/nodes/foreman.cp.lsst.org_spec.rb
Labels: enhancement

#1012 (role/ipareplica) bump ipa-server to 4.6.8-5.el7.centos.15
  hieradata/role/ipareplica.yaml
  hieradata/role/ipareplica/osfamily/RedHat/major/7.yaml
  spec/hosts/roles/ipareplica_spec.rb
Labels: enhancement, live-hosts

#1013 (profile::ts::rpi) unused
  site/profile/manifests/ts/rpi.pp
  spec/classes/ts/rpi_spec.rb
Labels: enhancement

#1014 (vpn{1-2}.ls) Network configuration and tests
  hieradata/node/vpn1.ls.lsst.org.yaml
  hieradata/node/vpn2.ls.lsst.org.yaml
  spec/hosts/nodes/vpn1.ls.lsst.org_spec.rb
  spec/hosts/nodes/vpn2.ls.lsst.org_spec.rb
Labels: enhancement

#1015 (comcam-lion04.cp) Summit Deployment
  hieradata/node/comcam-lion04.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-lion04.cp.lsst.org_spec.rb
Labels: enhancement

#1017 (cluster/comcam-ccs) packages rh-git218 and devtoolset-8 are rhel7 only
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/comcam-ccs/osfamily/RedHat/major/7.yaml
Labels: enhancement, ccs

#998 (auxtel-hcu02.cp) OS Redeployment
  hieradata/node/auxtel-hcu02.cp.lsst.org.yaml
  spec/hosts/nodes/auxtel-hcu02.cp.lsst.org_spec.rb
Labels: enhancement
