Repository lsst-it/lsst-control, pull requests merged in 2023-10, with the labels that each got.

#937 (common) enable sssd startup of services; disable socket activation
  hieradata/common.yaml
  site/profile/manifests/core/common.pp
  site/profile/manifests/core/ipa.pp
  site/profile/manifests/core/sssd.pp
  spec/classes/archive/commmon_spec.rb
  spec/classes/core/common_spec.rb
  spec/classes/core/sssd_spec.rb
  spec/spec_helper.rb
  spec/support/spec/sssd.rb
Labels: bug

#938 (node/lsstcam-{mcm,db01}.cp.lsst.org) mv to vlan1511; add dds interface
  hieradata/node/lsstcam-db01.cp.lsst.org.yaml
  hieradata/node/lsstcam-mcm.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-db01.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-mcm.cp.lsst.org_spec.rb
  spec/spec_helper.rb
Labels: enhancement, live-hosts

#936 rke client version bump for dev clusters
  hieradata/cluster/ayekan.yaml
  hieradata/cluster/ruka.yaml
  hieradata/site/dev/role/rke.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/ayekan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#939 (role/ccs-mcm) update CCSWebTrending.war version
  hieradata/role/ccs-mcm.yaml
Labels: bug, ccs

#940 (role/foreman) disable fips mode by default
  hieradata/role/foreman.yaml
  spec/spec_helper.rb
Labels: bug

#944 (Puppetfile) bump lsst/* mods to allow puppet/systemd 6.x
  Puppetfile
Labels: enhancement

#943 (site/cp/role/hypervisor) add br1102 interface
  hieradata/site/cp/role/hypervisor.yaml
  spec/hosts/nodes/core01.cp.lsst.org_spec.rb
  spec/hosts/nodes/core02.cp.lsst.org_spec.rb
  spec/hosts/nodes/core03.cp.lsst.org_spec.rb
Labels: enhancement

#945 (spec) test on el9 by default
  hieradata/cluster/auxtel-ccs/osfamily/RedHat/major/9.yaml
  hieradata/role/perfsonar/osfamily/RedHat/major/9.yaml
  hieradata/role/puppetdb/osfamily/RedHat/major/9.yaml
  metadata.json
  spec/classes/ccs/el9_spec.rb
  spec/classes/ccs/graphical_spec.rb
  spec/classes/core/x2go_spec.rb
  spec/hosts/nodes/ayekan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
  spec/hosts/nodes/core01.cp.lsst.org_spec.rb
  spec/hosts/nodes/core01.dev.lsst.org_spec.rb
  spec/hosts/nodes/core02.cp.lsst.org_spec.rb
  spec/hosts/nodes/core02.dev.lsst.org_spec.rb
  spec/hosts/nodes/core03.cp.lsst.org_spec.rb
  spec/hosts/nodes/core03.dev.lsst.org_spec.rb
  spec/hosts/nodes/core1.tu.lsst.org_spec.rb
  spec/hosts/nodes/core2.tu.lsst.org_spec.rb
  spec/hosts/nodes/core3.tu.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/luan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka04.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka06.dev.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
  spec/hosts/roles/atshcu_spec.rb
  spec/hosts/roles/bastion_spec.rb
  spec/hosts/roles/ccs_dc_spec.rb
  spec/hosts/roles/ccs_desktop_spec.rb
  spec/hosts/roles/ccs_hcu_spec.rb
  spec/hosts/roles/ccs_mcm_spec.rb
  spec/hosts/roles/ccs_viswork_spec.rb
  spec/hosts/roles/comcam_fp_spec.rb
  spec/hosts/roles/foreman_spec.rb
  spec/hosts/roles/hexrot_spec.rb
  spec/hosts/roles/hvac_spec.rb
  spec/hosts/roles/hypervisor_spec.rb
  spec/hosts/roles/m1m3_spec.rb
  spec/hosts/roles/rke_spec.rb
  spec/hosts/roles/sal_dx_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#909 (chango) add network config and role
  hieradata/cluster/chango.yaml
  spec/hosts/nodes/chango01.ls.lsst.org_spec.rb
Labels: enhancement

#954 (role/ccs-ds) install file transfer utils globally, not just on ls
  hieradata/role/ccs-dc.yaml
  hieradata/site/ls/role/ccs-dc.yaml
Labels: enhancement, ccs

#947 (role/rke) add make package
  hieradata/role/rke.yaml
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#948 (node/dns[123].dev.lsst.org) convert net config to EL9
  hieradata/node/dns1.dev.lsst.org.yaml
  hieradata/node/dns2.dev.lsst.org.yaml
  hieradata/node/dns3.dev.lsst.org.yaml
  spec/hosts/nodes/dns1.dev.lsst.org_spec.rb
  spec/hosts/nodes/dns2.dev.lsst.org_spec.rb
  spec/hosts/nodes/dns3.dev.lsst.org_spec.rb
Labels: enhancement, live-hosts

#949 (node/dns[123].tu.lsst.org) convert net config to EL9
  hieradata/node/dns1.tu.lsst.org.yaml
  hieradata/node/dns2.tu.lsst.org.yaml
  hieradata/node/dns3.tu.lsst.org.yaml
  spec/hosts/nodes/dns1.tu.lsst.org_spec.rb
  spec/hosts/nodes/dns2.tu.lsst.org_spec.rb
  spec/hosts/nodes/dns3.tu.lsst.org_spec.rb
Labels: enhancement, live-hosts

#956 (cluster/*ccs) rm disabling of sudo config purging
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  spec/spec_helper.rb
Labels: bug

#950 (node/dns[123].cp.lsst.org) convert net config to EL9
  hieradata/node/dns1.cp.lsst.org.yaml
  hieradata/node/dns2.cp.lsst.org.yaml
  hieradata/node/dns3.cp.lsst.org.yaml
  spec/hosts/nodes/dns1.cp.lsst.org_spec.rb
  spec/hosts/nodes/dns2.cp.lsst.org_spec.rb
  spec/hosts/nodes/dns3.cp.lsst.org_spec.rb
Labels: enhancement, live-hosts

#957 (.puppet-lint.rc) disable legacy_facts check
  .puppet-lint.rc
  Gemfile
Labels: enhancement

#953 (node/core0[123].ls.lsst.org) add 1114s based servers
  hieradata/node/core01.ls.lsst.org.yaml
  hieradata/node/core02.ls.lsst.org.yaml
  hieradata/node/core03.ls.lsst.org.yaml
  hieradata/site/ls/role/hypervisor.yaml
  site/profile/manifests/core/common.pp
  spec/hosts/nodes/core01.ls.lsst.org_spec.rb
  spec/hosts/nodes/core02.ls.lsst.org_spec.rb
  spec/hosts/nodes/core03.ls.lsst.org_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#955 new ccs releases for ccs clusters
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#958 (node/dns[123].ls.lsst.org) convert net config to EL9
  hieradata/node/dns1.ls.lsst.org.yaml
  hieradata/node/dns2.ls.lsst.org.yaml
  hieradata/node/dns3.ls.lsst.org.yaml
  spec/hosts/nodes/dns1.ls.lsst.org_spec.rb
  spec/hosts/nodes/dns2.ls.lsst.org_spec.rb
  spec/hosts/nodes/dns3.ls.lsst.org_spec.rb
Labels: enhancement

#959 (Puppetfile) replace ghoneycutt/hosts with puppet/hosts
  Puppetfile
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/common.yaml
  hieradata/node/auxtel-daq-mgt.cp.lsst.org.yaml
  hieradata/node/comcam-daq-mgt.cp.lsst.org.yaml
  hieradata/node/daq-mgt.tu.lsst.org.yaml
  hieradata/role/ipareplica.yaml
  spec/hosts/nodes/auxtel-daq-mgt-cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-daq-mgt-cp.lsst.org_spec.rb
  spec/hosts/nodes/daq-mgt.tu.lsst.org_spec.rb
Labels: enhancement

#961 (role/ipareplica) fix auto-fqdn /etc/hosts conflict with tailscale IP
  hieradata/role/ipareplica.yaml
  spec/hosts/roles/ipareplica_spec.rb
Labels: bug

#963 (cluster/*-ccs) change {ls,cp} smtp relay to exch-ls.lsst.org
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
Labels: enhancement

#962 (Puppetfile) bulk mod update; migrate to stdlib 9.x
  Puppetfile
  hieradata/common.yaml
  hieradata/node/ipa1.dev.lsst.org.yaml
  hieradata/node/ipa1.ls.lsst.org.yaml
  hieradata/node/ipa1.tu.lsst.org.yaml
  hieradata/role/cmms.yaml
  hieradata/role/ipareplica.yaml
  hieradata/role/ubuntu.yaml
  hieradata/site/cp.yaml
  hieradata/site/dev.yaml
  hieradata/site/dmz.yaml
  hieradata/site/ls.yaml
  hieradata/site/tu.yaml
  site/profile/manifests/core/common.pp
  site/profile/manifests/core/foreman.pp
  site/profile/manifests/core/ipa.pp
  site/profile/manifests/core/ipa_pwd_reset.pp
  site/profile/manifests/core/krb5.pp
  site/profile/manifests/core/rke.pp
  site/profile/manifests/core/sssd.pp
  spec/classes/archive/commmon_spec.rb
  spec/classes/core/common_spec.rb
  spec/classes/core/ipa_pwd_reset_spec.rb
  spec/classes/core/ipa_spec.rb
  spec/classes/core/krb5_spec.rb
  spec/classes/core/rke_spec.rb
  spec/classes/core/sssd_spec.rb
  spec/default_facts.yml
  spec/fixtures/hieradata/common.yaml
  spec/fixtures/hieradata/profile-only.yaml
  spec/spec_helper.rb
  spec/support/spec/sssd.rb
Labels: enhancement
