Repository lsst-it/lsst-control, pull requests merged in 2023-07, with the labels that each got.

#864 (role/hypervisor) fix libvirt configuration on EL >= 9.2
  Puppetfile
  hieradata/role/hypervisor/osfamily/RedHat/major/9.yaml
  hieradata/site/dev/role/hypervisor/osfamily/RedHat/major/7.yaml
  hieradata/site/dev/variant/r430.yaml
  hieradata/site/dev/variant/r430/subvariant/hypervisor.yaml
  spec/hosts/nodes/core01.dev.lsst.org_spec.rb
  spec/hosts/nodes/core02.dev.lsst.org_spec.rb
  spec/hosts/nodes/core03.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka06.dev.lsst.org_spec.rb
Labels: bug

#866 (rancher.dev) dhcp on ens3 interface and tests
  hieradata/cluster/rancher.yaml
  spec/hosts/nodes/rancher01.dev.lsst.org_spec.rb
Labels: enhancement

#867 (profile::core::common) add rsync & parallel packages
  site/profile/data/common.yaml
  spec/spec_helper.rb
Labels: enhancement

#870 It 4622/auxtel lsstcam software
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/ls/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
Labels: enhancement, ccs

#871 It 4614 daq r5 v6.7
  hieradata/node/auxtel-daq-mgt.cp.lsst.org.yaml
  hieradata/node/comcam-daq-mgt.cp.lsst.org.yaml
  hieradata/role/daq-mgt.yaml
  hieradata/site/ls/role/daq-mgt.yaml
  hieradata/site/tu/role/daq-mgt.yaml
  spec/hosts/nodes/auxtel-daq-mgt-cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-daq-mgt-cp.lsst.org_spec.rb
  spec/hosts/nodes/daq-mgt.tu.lsst.org_spec.rb
Labels: enhancement, daq

#872 (ccs/lsstcam) misc improvements
  Puppetfile
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/common.yaml
  hieradata/node/lsstcam-dc01.ls.lsst.org.yaml
  hieradata/node/lsstcam-dc06.ls.lsst.org.yaml
  hieradata/node/lsstcam-mcm.ls.lsst.org.yaml
  hieradata/site/ls/role/ccs-dc.yaml
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
Labels: enhancement, ccs

#873 (ccs) new software release for auxtel and comcam clusters
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#874 (profile::ccs::common) move packages here from ccs cluster files
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  site/profile/data/common.yaml
Labels: enhancement, ccs

#875 (*) misc bug fixes related to migrating away from example42/network
  README.md
  hiera.yaml
  hieradata/cluster/ruka/variant/r430.yaml
  hieradata/cluster/ruka/variant/r440.yaml
  hieradata/role/ubuntu.yaml
  site/profile/manifests/core/common.pp
  site/profile/manifests/core/ifdown.pp
  spec/classes/core/ifdown_spec.rb
  spec/fixtures/hiera.yaml
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka04.dev.lsst.org_spec.rb
Labels: bug

#812 (cluster/ruka) rke version bump 1.4.6-rc4
  hieradata/cluster/ruka.yaml
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
Labels: enhancement

#878 (cluster/ruka) add el8+ network config support
  hieradata/cluster/ruka.yaml
  hieradata/cluster/ruka/osfamily/RedHat/major/7.yaml
  hieradata/cluster/ruka/variant/r430.yaml
  hieradata/cluster/ruka/variant/r440.yaml
  hieradata/site/dev/variant/r440.yaml
  site/profile/manifests/core/lhnrouting.pp
  spec/classes/core/lhnrouting_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka04.dev.lsst.org_spec.rb
Labels: enhancement

#876 (ayekan.ls) Initial network config and role
  hieradata/cluster/ayekan.yaml
  hieradata/cluster/ayekan/role/rke.yaml
  spec/hosts/nodes/ayekan01.ls.lsst.org_spec.rb
Labels: enhancement
