Repository lsst-it/lsst-control, pull requests merged in 2023-04, with the labels that each got.

#773 (node/lsstcam-db01) run ccs services localdb and rest-server
  hieradata/node/lsstcam-db01.cp.lsst.org.yaml
  hieradata/node/lsstcam-db01.ls.lsst.org.yaml
  spec/hosts/nodes/auxtel-mcm.ls.lsst.org_spec.rb
  spec/hosts/nodes/azar01.ls.lsst.org_spec.rb
  spec/hosts/nodes/gis-bastion01.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-archiver.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-daq-mgt.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-db01.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-db01.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-vs01.ls.lsst.org_spec.rb
  spec/spec_helper.rb
Labels: enhancement, ccs

#779 (cluster/comcam-ccs) no longer set ccs publish.config.info
  hieradata/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#780 (cluster/comcam-ccs) revert removal of ccs publish.config.info
  hieradata/cluster/comcam-ccs.yaml
Labels: bug, ccs

#778 (chonchon) add LHN network config vlan1800
  hieradata/cluster/chonchon.yaml
  hieradata/cluster/chonchon/role/rke.yaml
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
Labels: enhancement

#781 (chonchon) correct vlan interface fix
  hieradata/cluster/chonchon.yaml
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
Labels: bug

#784 (dimm.cp) add NFS mount and telnet
  hieradata/role/dimm.yaml
  spec/hosts/roles/dimm_spec.rb
Labels: enhancement

#782 (common) add csilva_b account
  hieradata/common.yaml
  spec/spec_helper.rb
Labels: enhancement

#783 (role/rucio) fwv
  Puppetfile
  hieradata/role/rucio.yaml
  hieradata/site/dmz.yaml
  site/profile/manifests/core/dmz.pp
  site/profile/manifests/core/rucio.pp
Labels: enhancement

#785 (cluster/*-ccs) fix version of OpenSpliceDDS on rhel8
  hieradata/cluster/auxtel-ccs/osfamily/RedHat/major/8.yaml
  hieradata/cluster/comcam-ccs/osfamily/RedHat/major/8.yaml
  hieradata/cluster/lsstcam-ccs/osfamily/RedHat/major/8.yaml
  spec/hosts/nodes/auxtel-mcm.ls.lsst.org_spec.rb
Labels: bug, ccs

#789 (ccs) small fixes for auxtel services
  hieradata/node/auxtel-fp01.cp.lsst.org.yaml
  hieradata/node/auxtel-fp01.ls.lsst.org.yaml
  hieradata/node/auxtel-fp01.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-fp01.ls.lsst.org_spec.rb
Labels: enhancement, ccs

#788 (namkueyen) add namkueyen config
  hieradata/cluster/namkueyen.yaml
  hieradata/cluster/namkueyen/role/rke.yaml
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
Labels: enhancement

#786 (profile::core::docker) fix ceph mons crashing on el9
  Puppetfile
  site/profile/manifests/core/docker.pp
  spec/classes/core/docker_spec.rb
Labels: bug, depends-on-another-pr, live-hosts

#791 (ccs) adjust settings of the ccs -ih service
  Puppetfile
  hieradata/node/auxtel-fp01.cp.lsst.org.yaml
  hieradata/node/auxtel-fp01.ls.lsst.org.yaml
  hieradata/node/auxtel-fp01.tu.lsst.org.yaml
  hieradata/node/comcam-fp01.cp.lsst.org.yaml
  hieradata/node/comcam-fp01.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-fp01.ls.lsst.org_spec.rb
Labels: enhancement, ccs

#793 (role/perfsonar) fix version pinning by controlling yumrepo url
  hieradata/role/perfsonar.yaml
  hieradata/role/perfsonar/osfamily/RedHat/major/7.yaml
  hieradata/role/perfsonar/osfamily/RedHat/major/8.yaml
  site/profile/manifests/core/perfsonar.pp
  spec/classes/core/perfsonar_spec.rb
  spec/hosts/roles/perfsonar_spec.rb
  spec/spec_helper.rb
Labels: bug

#794 (profile::core::perfsonar) rm perfSONAR yumrepo mirrorlist
  site/profile/manifests/core/perfsonar.pp
  spec/spec_helper.rb
Labels: bug

#795 (site/tu/role/daq-mgt) update TTS to DAQ R5-V6.1
  hieradata/site/tu/role/daq-mgt.yaml
  spec/hosts/roles/daq_mgt_spec.rb
Labels: enhancement, daq

#797 (profile::ccs::graphical) rm libvirt-daemon package
  site/profile/manifests/ccs/graphical.pp
  spec/classes/ccs/graphical_spec.rb
Labels: enhancement

#799 (site/ls/role/daq-mgt) daq v6.1
  hieradata/site/ls/role/daq-mgt.yaml
Labels: enhancement, daq

#796 (hiera) add site variant and subvariant layers
  README.md
  hiera.yaml
  spec/fixtures/hiera.yaml
Labels: enhancement

#798 (role/ccs-dc) include profile::core::debugutils
  hieradata/role/ccs-dc.yaml
  spec/hosts/roles/ccs_dc_spec.rb
Labels: enhancement

#800 (profile::daq::daq_interface) drop EL8+ support
  hieradata/role/atsccs.yaml
  hieradata/role/atsccs/osfamily/RedHat/major/7.yaml
  hieradata/role/atsdaq.yaml
  hieradata/role/atsdaq/osfamily/RedHat/major/7.yaml
  hieradata/role/ccs-dc.yaml
  hieradata/role/ccs-dc/osfamily/RedHat/major/7.yaml
  hieradata/role/comcam-fp.yaml
  hieradata/role/comcam-fp/osfamily/RedHat/major/7.yaml
  hieradata/role/daq-mgt.yaml
  hieradata/role/daq-mgt/osfamily/RedHat/major/7.yaml
  site/profile/manifests/daq/daq_interface.pp
  spec/classes/daq/daq_interface_spec.rb
  spec/hosts/roles/ccs_dc_spec.rb
  spec/spec_helper.rb
Labels: enhancement, ccs, daq

#790 (site/ls) refactor and dedup NetworkManger configuration
  hieradata/cluster/konkong.yaml
  hieradata/cluster/kueyen.yaml
  hieradata/cluster/manke.yaml
  hieradata/cluster/namkueyen.yaml
  hieradata/cluster/pillan/osfamily/RedHat/major/9.yaml
  hieradata/node/auxtel-archiver.ls.lsst.org.yaml
  hieradata/node/auxtel-dc01.ls.lsst.org.yaml
  hieradata/node/auxtel-fp01.ls.lsst.org.yaml
  hieradata/node/auxtel-mcm.ls.lsst.org.yaml
  hieradata/node/azar01.ls.lsst.org.yaml
  hieradata/node/dimm.cp.lsst.org.yaml
  hieradata/node/lsstcam-archiver.ls.lsst.org.yaml
  hieradata/node/lsstcam-daq-mgt.ls.lsst.org.yaml
  hieradata/node/lsstcam-db01.ls.lsst.org.yaml
  hieradata/node/lsstcam-mcm.ls.lsst.org.yaml
  hieradata/node/lsstcam-vs01.ls.lsst.org.yaml
  hieradata/node/tel-hw1.ls.lsst.org.yaml
  hieradata/site/dev/role/hypervisor/osfamily/RedHat/major/9.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
  hieradata/site/ls/variant/1114s.yaml
  hieradata/site/ls/variant/1114s/subvariant/daq-lhn.yaml
  hieradata/site/ls/variant/1114s/subvariant/dds.yaml
  spec/hosts/nodes/auxtel-archiver.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-fp01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-mcm.ls.lsst.org_spec.rb
  spec/hosts/nodes/azar01.ls.lsst.org_spec.rb
  spec/hosts/nodes/dimm.cp.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.ls.lsst.org_spec.rb
  spec/hosts/nodes/love01.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-archiver.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-daq-mgt.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-db01.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-mcm.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-vs01.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/ruka06.dev.lsst.org_spec.rb
  spec/hosts/nodes/tel-hw1.ls.lsst.org_spec.rb
  spec/spec_helper.rb
Labels: enhancement, ccs, daq, live-hosts

#802 (node/perfsonar.cp) add network config and routes
  hieradata/node/perfsonar1.cp.lsst.org.yaml
  spec/hosts/nodes/perfsonar1.cp.lsst.org_spec.rb
Labels: enhancement

#801 (node/azar03.cp) update network config
  hieradata/node/azar03.cp.lsst.org.yaml
  spec/hosts/nodes/azar03.cp.lsst.org_spec.rb
Labels: enhancement

#803 (hiera) enable eyaml support
  hiera.yaml
  site/profile/manifests/core/puppet_master.pp
  spec/spec_helper.rb
Labels: enhancement

#805 (role/dimm) fix file/dir ownership; fix serial device ownership
  hieradata/common.yaml
  hieradata/role/dimm.yaml
  spec/hosts/roles/dimm_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#806 (role/perfsonar) version update to 4.4.6
  hieradata/role/perfsonar.yaml
  spec/hosts/roles/perfsonar_spec.rb
Labels: enhancement

#808 (node/perfsonar1.ls.lsst.org) clean up lhn routing
  hieradata/node/perfsonar1.ls.lsst.org.yaml
  spec/hosts/nodes/perfsonar1.ls.lsst.org_spec.rb
Labels: bug

#809 (role/daq-mgt) Update ComCam to DAQ R5-V6.1
  hieradata/node/comcam-daq-mgt.cp.lsst.org.yaml
  spec/hosts/roles/daq_mgt_spec.rb
Labels: enhancement, daq
