Repository lsst-it/lsst-control, pull requests merged in 2024-04, with the labels that each got.

#1105 (node/fiber-spec01.tu.lsst.org) EL9 setup
  hieradata/node/fiber-spec01.tu.lsst.org.yaml
  spec/hosts/nodes/fiber-spec01.tu.lsst.org_spec.rb
Labels: enhancement

#1107 (role/puppetdb) bump postgresql to 15
  hieradata/role/puppetdb.yaml
  site/profile/manifests/core/puppetdb.pp
  spec/hosts/roles/puppetdb_spec.rb
Labels: bug

#1108 (profile::core::puppetboard) fwv
  hieradata/role/puppetdb.yaml
  site/profile/manifests/core/puppetboard.pp
  spec/fixtures/hieradata/common.yaml
  spec/hosts/roles/puppetdb_spec.rb
Labels: enhancement

#1104 (cluster/yagan) add br1101 for htcondor
  hieradata/cluster/yagan/variant/1114s.yaml
  hieradata/cluster/yagan/variant/1114s/subvariant/1.01.yaml
  hieradata/cluster/yagan/variant/1114s/subvariant/1.02.yaml
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
Labels: enhancement

#1111 (ccs) add some new CCS releases
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1112 (*) mark [some] parameters with secrets as Sensitive
  Puppetfile
  site/profile/manifests/ccs/cfs.pp
  site/profile/manifests/ccs/common.pp
  site/profile/manifests/ccs/el9.pp
  site/profile/manifests/ccs/file_transfer.pp
  site/profile/manifests/ccs/graphical.pp
  site/profile/manifests/ccs/postfix.pp
  site/profile/manifests/core/ipam.pp
  site/profile/manifests/core/letsencrypt.pp
  site/profile/manifests/core/puppetboard.pp
  site/profile/manifests/core/yum/lsst_ts_private.pp
  site/profile/templates/ccs/file_transfer/s3daemon_envfile.epp
  spec/classes/ccs/file_transfer_spec.rb
  spec/classes/core/letsencrypt_spec.rb
  spec/classes/core/yum/lsst_ts_private_spec.rb
  spec/fixtures/hieradata/common.yaml
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/hosts/roles/comcam_fp_spec.rb
Labels: enhancement

#1113 (role/ccs-mcm) install tomcat library jar files
  hieradata/role/ccs-mcm.yaml
  site/profile/manifests/ccs/tomcat.pp
Labels: enhancement, ccs

#1115 (role/puppetdb) enable ldap auth
  hieradata/role/puppetdb.yaml
  hieradata/site/cp/role/puppetdb.yaml
  hieradata/site/tu/role/puppetdb.yaml
  site/profile/manifests/core/puppetboard.pp
  site/profile/manifests/core/puppetdb.pp
  spec/fixtures/hieradata/common.yaml
  spec/hosts/roles/puppetdb_spec.rb
Labels: enhancement

#1114 (role/ats{ccs|daq}) add ccs graphical profile
  hieradata/role/atsccs.yaml
  hieradata/role/atsdaq.yaml
Labels: enhancement, ccs

#1086 (ccs) test using kafka for sal on comcam-mcm.tu
  Puppetfile
  hieradata/node/comcam-mcm.tu.lsst.org.yaml
Labels: enhancement, ccs

#1116 (site/dev) rm rsyslog -> opensearch
  hieradata/site/dev.yaml
  spec/support/spec/rsyslog.rb
Labels: bug

#1121 (site/dev) rm rsyslog -> opensearch -- part2
  hieradata/site/dev.yaml
  spec/support/spec/rsyslog.rb
Labels: bug

#1119 (role/tang) add cp site support
  hieradata/common.yaml
  hieradata/node/tang01.cp.lsst.org.yaml
  hieradata/node/tang02.cp.lsst.org.yaml
  hieradata/node/tang03.cp.lsst.org.yaml
  hieradata/site/cp/role/foreman.yaml
  hieradata/site/cp/role/tang.yaml
  spec/hosts/nodes/tang01.cp.lsst.org_spec.rb
  spec/hosts/nodes/tang02.cp.lsst.org_spec.rb
  spec/hosts/nodes/tang03.cp.lsst.org_spec.rb
  spec/hosts/roles/tang_spec.rb
  spec/support/spec/ipset.rb
Labels: enhancement

#1124 (node/lsstcam-mcm.ls.lsst.org) update network to pure yaml format
  hieradata/site/ls/variant/1114s/subvariant/dds.yaml
Labels: enhancement

#1122 (site/cp/cluster/rancher) add network config
  hieradata/site/cp/cluster/rancher.yaml
  hieradata/site/cp/cluster/rancher/role/rke.yaml
  spec/hosts/nodes/rancher01.cp.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.ls.lsst.org_spec.rb
Labels: enhancement

#1120 (lsstcam-dc*.ls) EL9 upgrade lsstcam nodes
  hieradata/site/ls/variant/1114s.yaml
  hieradata/site/ls/variant/1114s/subvariant/daq-lhn.yaml
Labels: enhancement

#1126 (role/rke) only support el9
  spec/classes/core/rke_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1127 (site/dev) bump rke to 1.5.8
  hieradata/site/dev/role/rke.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/ayekan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1094 (role/htcondor) installs htcondor scheduler
  Puppetfile
  hieradata/role/htcondor.yaml
  hieradata/site/cp/role/htcondor.yaml
  hieradata/site/dev/role/htcondor.yaml
  hieradata/site/ls/role/htcondor.yaml
  spec/hosts/roles/htcondor_spec.rb
Labels: enhancement

#1128 (Puppetfile) bump version of ccs_monit
  Puppetfile
Labels: bug, ccs

#1129 (node/foreman.cp) increase dhcp pool vlan 1310
  hieradata/node/foreman.cp.lsst.org.yaml
  spec/hosts/nodes/foreman.cp.lsst.org_spec.rb
Labels: enhancement

#1131 (role/laserrpi.yaml) add profile::pi::ftdi
  hieradata/role/laserrpi.yaml
  spec/hosts/roles/laserrpi_spec.rb
Labels: enhancement

#1132 (role/foreman) disable Foreman_global_parameter[disk_enc_tang_servers]
  hieradata/site/cp/role/foreman.yaml
  hieradata/site/dev/role/foreman.yaml
  hieradata/site/ls/role/foreman.yaml
  hieradata/site/tu/role/foreman.yaml
Labels: bug

#1130 (site/dev) allow ruka to scrape dev node_exporter instances
  hieradata/site/dev.yaml
  spec/support/spec/firewall.rb
Labels: enhancement

#1135 (core[1-3].cp.lsst.org) clean up old cores
  hieradata/node/core1.cp.lsst.org.yaml
  hieradata/node/core2.cp.lsst.org.yaml
  hieradata/node/core3.cp.lsst.org.yaml
  spec/hosts/nodes/core1.cp.lsst.org_spec.rb
  spec/hosts/nodes/core2.cp.lsst.org_spec.rb
  spec/hosts/nodes/core3.cp.lsst.org_spec.rb
Labels: enhancement

#1134 (profile::core::fiberspec) add spectrometer udev rule
  hieradata/role/fiberspec.yaml
  site/profile/manifests/core/fiberspec.pp
  spec/classes/core/fiberspec_spec.rb
  spec/support/spec/fiberspec.rb
Labels: enhancement

#1136 (role/htcondor) update config and dry up tests
  hieradata/role/htcondor.yaml
  hieradata/site/cp/role/htcondor.yaml
  hieradata/site/dev/role/htcondor.yaml
  hieradata/site/ls/role/htcondor.yaml
  spec/hosts/roles/htcondor_spec.rb
Labels: enhancement

#1133 (profile/archive) remove sysctl:lhn
  site/profile/manifests/archive/common.pp
  spec/hosts/roles/auxtel_archiver_spec.rb
  spec/hosts/roles/comcam_archiver_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#1137 (lsst-control) add license file to repo
  LICENSE
Labels: enhancement
