Repository lsst-it/lsst-control, pull requests merged in 2024-10, with the labels that each got.

#1478 (role/rke2{agent,server}) update backup dirs to include rke2 tls certs
  hieradata/role/rke2agent.yaml
  hieradata/role/rke2server.yaml
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
Labels: enhancement

#1485 (role/htcondor) fix comcam-archiver NFS to nfs3.cp
  hieradata/site/cp/role/htcondor.yaml
  spec/hosts/roles/htcondor_spec.rb
Labels: enhancement

#1483 (node/comcam-archiver.cp) add EL9 network configuration & tests
  hieradata/node/comcam-archiver.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-archiver.cp.lsst.org_spec.rb
Labels: enhancement

#1486 (site/tu) bump rke to 1.6.2 for k8s rke v1.29.8
  hieradata/site/tu/role/rke.yaml
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.tu.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1491 (role/rke) bump LS client to v1.6.2
  hieradata/site/ls/role/rke.yaml
  spec/hosts/nodes/antu01.ls.lsst.org_spec.rb
  spec/hosts/nodes/chango01.ls.lsst.org_spec.rb
  spec/hosts/nodes/gaw01.ls.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.ls.lsst.org_spec.rb
  spec/hosts/nodes/luan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.ls.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1492 (cluster/{auxtel|comcam|lsstcam}-ccs) switch alerts to Rubin Slack
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  spec/hosts/nodes/lsstcam-db01.cp.lsst.org_spec.rb
Labels: enhancement, ccs

#1493 (site/ls/role/ccs-dc) use a branch version of s3daemon
  hieradata/site/ls/role/ccs-dc.yaml
Labels: enhancement, ccs

#1494 (ccs_software::influx_url) add site-specific settings
  hieradata/site/cp.yaml
  hieradata/site/ls.yaml
  hieradata/site/tu.yaml
Labels: enhancement, ccs

#1498 (site/{ls,tu}/{auxtel|comcam|lsstcam}-ccs) alerts to Rubin Slack
  hieradata/site/ls/cluster/auxtel-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
  spec/hosts/nodes/auxtel-mcm.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-db01.ls.lsst.org_spec.rb
Labels: enhancement, ccs

#1499 (Puppetfile) fix clustershell sha
  Puppetfile
Labels: bug

#1496 (site/ls/role/ccs-dc) go back to s3daemon main branch
  hieradata/site/ls/role/ccs-dc.yaml
Labels: bug, ccs

#1500 (node/lsstcam-fcs.cp) add ccs services
  hieradata/node/lsstcam-fcs.cp.lsst.org.yaml
Labels: enhancement, ccs

#1509 (profile::ccs::file_transfer) default s3daemon to true
  hieradata/cluster/lsstcam-ccs/role/ccs-dc.yaml
  hieradata/node/comcam-fp01.tu.lsst.org.yaml
  site/profile/manifests/ccs/file_transfer.pp
Labels: enhancement, ccs

#1511 (cluster/auxtel-ccs) prune list of ccs releases to install
  hieradata/cluster/auxtel-ccs.yaml
Labels: enhancement, ccs

#1512 (cluster/auxtel-ccs) remove non-existent hcu02 from clustershell
  hieradata/cluster/auxtel-ccs.yaml
Labels: bug, ccs

#1515 (*) change the priority variable from a String to an integer
  hieradata/common.yaml
Labels: bug

#1516 (node/auxtel-mcm.cp, site/cp/role/ccs-mcm) fix kafka service name
  hieradata/node/auxtel-mcm.cp.lsst.org.yaml
  hieradata/site/cp/role/ccs-mcm.yaml
Labels: bug, ccs

#1519 (common/rke2) bump rke2 to v1.29.9 global
  hieradata/common.yaml
  hieradata/site/dev/role/rke2agent.yaml
  hieradata/site/dev/role/rke2server.yaml
  spec/hosts/nodes/elqui01.cp.lsst.org_spec.rb
  spec/hosts/nodes/elqui06.cp.lsst.org_spec.rb
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
Labels: enhancement
