Repository lsst-it/lsst-control, pull requests merged in 2024-12, with the labels that each got.

#1554 (role/hexrot) fix nexus packages for hexrot
  hieradata/role/hexrot.yaml
  site/profile/data/common.yaml
  site/profile/manifests/core/ni_packages.pp
  spec/support/spec/nexusctio.rb
  spec/support/spec/ni_packages.rb
Labels: enhancement

#1555 (role/auxtelmcm) remove tomcat profile
  hieradata/role/auxtelmcm.yaml
Labels: enhancement

#1556 (cluster/auxtel-ccs) add new ccs release
  hieradata/cluster/auxtel-ccs.yaml
Labels: enhancement, ccs

#1541 (perfsonar.cp) network config for EL9
  hieradata/node/perfsonar1.cp.lsst.org.yaml
  hieradata/role/perfsonar.yaml
  hieradata/role/perfsonar/osfamily/RedHat/major/8.yaml
  spec/hosts/nodes/perfsonar1.cp.lsst.org_spec.rb
  spec/hosts/roles/perfsonar_spec.rb
Labels: enhancement

#1560 (node/foreman.cp) bump yagan lhn dchp range
  hieradata/node/foreman.cp.lsst.org.yaml
  spec/hosts/nodes/foreman.cp.lsst.org_spec.rb
Labels: enhancement

#1558 (role/auxtel-hcu) add advec kernel module
  hieradata/role/auxtel-hcu.yaml
Labels: enhancement, ccs

#1564 (role/auxtel-hcu) change ccs ats-power service from dev to prod
  hieradata/role/auxtel-hcu.yaml
Labels: bug, ccs

#1565 (cluster/{auxtel|comcam|lsstcam}-ccs) add property for influx tag
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1570 (node/lsstcam-pcs02.cp) add refrig service
  hieradata/node/lsstcam-pcs02.cp.lsst.org.yaml
Labels: enhancement, ccs

#1563 (cluster/pillan) convert from rke1 -> rke2
  hieradata/cluster/pillan.yaml
  hieradata/cluster/pillan/role/rke2agent.yaml
  hieradata/cluster/pillan/role/rke2server.yaml
  hieradata/node/pillan08.tu.lsst.org.yaml
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
Labels: enhancement

#1572 (cluster/pillan) remove ip rule for 140.252.147.192/27
  hieradata/cluster/pillan.yaml
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
Labels: bug

#1561 (role/auxtelmcm) add ccs_database
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/role/auxtelmcm.yaml
  site/profile/manifests/core/auxtelmcm.pp
  spec/classes/core/auxtelmcm_spec.rb
  spec/hosts/roles/auxtelmcm_spec.rb
  spec/support/spec/auxtelmcm.rb
Labels: enhancement

#1588 (node/auxtel-dc01.cp) add EL9 network configuration & tests
  hieradata/node/auxtel-dc01.cp.lsst.org.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
Labels: enhancement

#1531 (node/nfs3.cp.lsst.org) add nodes to export list
  hieradata/node/nfs3.cp.lsst.org.yaml
  spec/hosts/nodes/nfs3.cp.lsst.org_spec.rb
Labels: enhancement

#1594 (Puppetfile) Fix Puppetfile
  Puppetfile
Labels: bug

#1592 (node/hvac.cp.lsst.org) add el9 host
  hieradata/node/hvac.cp.lsst.org.yaml
  hieradata/role/niagara.yaml
  spec/hosts/nodes/hvac.cp.lsst.org_spec.rb
  spec/hosts/roles/niagara_spec.rb
Labels: enhancement
