Repository lsst-it/lsst-control, pull requests merged in 2024-02, with the labels that each got.

#1040 (gis-bastion01.cp) EL9 redeployment of GIS-Bastion01
  hieradata/node/gis-bastion01.cp.lsst.org.yaml
  spec/hosts/nodes/gis-bastion01.cp.lsst.org_spec.rb
Labels: enhancement

#1042 (ccs) add some ccs releases
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1043 (ccs) set daq client version to R5-V8.1
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1044 (node/comcam-dmctl01.cp) remove network config
  hieradata/node/comcam-dmctl01.cp.lsst.org.yaml
Labels: enhancement

#1045 (node/comcam-mcm.{cp,tu}) add lockmanager service
  hieradata/node/comcam-mcm.cp.lsst.org.yaml
  hieradata/node/comcam-mcm.tu.lsst.org.yaml
Labels: enhancement, ccs

#1050 (profile::core::docker) fix docker 24.x compatibility
  site/profile/manifests/core/docker.pp
  spec/spec_helper.rb
Labels: enhancement

#1052 (site/dev) bump docker to 24.0.9
  hieradata/site/dev.yaml
  spec/classes/core/docker_spec.rb
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/spec_helper.rb
  spec/support/spec/docker.rb
Labels: enhancement

#1053 (site/tu/role/rke) bump docker to 24.0.9
  hieradata/site/ls/cluster/rancher.yaml
  hieradata/site/tu/role/rke.yaml
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.ls.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.tu.lsst.org_spec.rb
Labels: enhancement

#1057 (spec) fix pillan/tu spec for rke 1.4.6
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: bug

#1058 (gha) update workflows to allow branch push or PR
  .github/workflows/arborist.yaml
  .github/workflows/block_merge_commits.yaml
  .github/workflows/commit_messages.yaml
  .github/workflows/librarian_puppet.yaml
  .github/workflows/markdownlint.yaml
  .github/workflows/pr_labels.yaml
  .github/workflows/rake_checks.yaml
  .github/workflows/shellcheck.yaml
  .github/workflows/yamllint.yaml
Labels: enhancement

#1048 profile::core::foreman: Make smee installation opt-out
  site/profile/manifests/core/foreman.pp
Labels: enhancement

#1049 profile::core::common: remove redundant ipa include
  site/profile/manifests/core/common.pp
Labels: bug

#1054 (comcam-dc01.tu.lsst.org) update network config to EL9
  hieradata/node/comcam-dc01.tu.lsst.org.yaml
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
Labels: enhancement

#1056 (comcam-fp01.tu) EL9 Network migration
  hieradata/node/comcam-fp01.tu.lsst.org.yaml
  spec/hosts/nodes/comcam-fp01.tu.lsst.org_spec.rb
Labels: enhancement

#1064 (role/auxtel-vent-gate) fwv
  hieradata/role/auxtel-vent-gate.yaml
  spec/hosts/roles/auxtel_vent_gate_spec.rb
Labels: enhancement

#1065 (node/foreman.tuc) add 140.252.147.109-113 to vlan3090 dhcp pool
  hieradata/node/foreman.tuc.lsst.cloud.yaml
  spec/hosts/nodes/foreman.tuc.lsst.cloud_spec.rb
Labels: enhancement

#1028 (profile::pi::gpsd) disable listening on ipv6 socket
  site/profile/manifests/pi/gpsd.pp
  spec/support/spec/gpsd.rb
Labels: bug

#1062 (auxtel-dc01.tu.lsst.org) EL9 network conversion
  hieradata/node/auxtel-dc01.tu.lsst.org.yaml
  hieradata/node/forwarders.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
Labels: enhancement

#1067 (daq-mgt.tu.lsst.org) EL8 Migration
  hieradata/node/daq-mgt.tu.lsst.org.yaml
  spec/hosts/nodes/daq-mgt.tu.lsst.org_spec.rb
Labels: enhancement

#1066 (ztp.ls.lsst.org) EL9 Redeployment.
  hieradata/node/ztp.ls.lsst.org.yaml
  spec/hosts/nodes/ztp.ls.lsst.org_spec.rb
Labels: enhancement

#1068 (role/auxtel-vent-gate) darken PI status LEDs
  hieradata/role/auxtel-vent-gate.yaml
  site/profile/manifests/pi/darkmode.pp
  spec/classes/pi/darkmode_spec.rb
  spec/hosts/roles/auxtel_vent_gate_spec.rb
  spec/support/spec/darkmode.rb
Labels: enhancement

#1070 (site/ls/role/rke) bump docker to 24.0.9
  hieradata/site/ls/cluster/rancher.yaml
  hieradata/site/ls/role/rke.yaml
  spec/hosts/nodes/ayekan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/gaw01.ls.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.lsst.org_spec.rb
  spec/hosts/nodes/luan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
Labels: enhancement

#1071 (gha) pin spec tests to use puppet 7.28.0 due to a 7.29.0 bug
  Gemfile
Labels: bug
