Repository lsst-it/lsst-control, pull requests merged in 2024-05, with the labels that each got.

#1139 (role/amor.yaml) update network config
  hieradata/site/cp/role/amor.yaml
  spec/hosts/nodes/love01.cp.lsst.org_spec.rb
Labels: enhancement

#1140 (cluster/ruka) add br2101 for htcondor
  hieradata/cluster/ruka.yaml
  hieradata/cluster/ruka/variant/r430.yaml
  hieradata/cluster/ruka/variant/r440.yaml
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka04.dev.lsst.org_spec.rb
Labels: enhancement

#1142 (node/foreman.ls.lsst.org) add new dhcp subnets
  hieradata/node/foreman.ls.lsst.org.yaml
  spec/hosts/nodes/foreman.ls.lsst.org_spec.rb
Labels: enhancement

#1144 (node/antu[01-04].ls.lsst.org) cluster configuration
  hieradata/cluster/antu.yaml
  hieradata/cluster/antu/role/rke.yaml
  hieradata/site/ls/variant/1115s.yaml
  site/profile/manifests/core/hardware.pp
  spec/hosts/nodes/antu01.ls.lsst.org_spec.rb
Labels: enhancement

#1148 (cluster/antu) bump rke to 1.5.8
  hieradata/cluster/antu/role/rke.yaml
  spec/hosts/nodes/antu01.ls.lsst.org_spec.rb
Labels: enhancement

#1146 (cluster/lsstcam-ccs) make java17 the default
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1141 (site/tu) bump rke to 1.5.8
  hieradata/site/tu/role/rke.yaml
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.tu.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1151 (cluster/lsstcam-ccs) no longer install old ccs releases
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1153 (site/dev) add ruka as a log destination
  hieradata/site/dev.yaml
  spec/support/spec/rsyslog.rb
Labels: enhancement

#1154 (site/ls) bump rke to 1.5.8
  hieradata/cluster/antu/role/rke.yaml
  hieradata/site/ls/role/rke.yaml
  spec/hosts/nodes/chango01.ls.lsst.org_spec.rb
  spec/hosts/nodes/gaw01.ls.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.ls.lsst.org_spec.rb
  spec/hosts/nodes/luan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.ls.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1157 (node/foreman.cp.lsst.org) deploy vlan 1700 LSSTCAM dhcp pool
  hieradata/node/foreman.cp.lsst.org.yaml
  spec/hosts/nodes/foreman.cp.lsst.org_spec.rb
Labels: enhancement

#1152 (profile::ccs::tomcat) add ccs webtrending and rest server
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/role/ccs-mcm.yaml
  site/profile/manifests/ccs/tomcat.pp
  site/profile/templates/ccs/tomcat/logging.properties.epp
  site/profile/templates/ccs/tomcat/statusPersister.properties.epp
  spec/classes/ccs/tomcat_spec.rb
Labels: enhancement, ccs

#1164 (Puppetfile) bump version of ccs_software
  Puppetfile
Labels: enhancement, ccs

#1166 (profile::ccs::graphical) tweak rpms
  site/profile/manifests/ccs/graphical.pp
Labels: enhancement, ccs

#1161 (node/lsstcam-shutter01.cp.lsst.org) Deploy host as EL9
  hieradata/node/lsstcam-shutter01.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-shutter01.cp.lsst.org_spec.rb
Labels: enhancement

#1163 (site/cp) bump rke to 1.5.8
  hieradata/role/rke.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1138 (role/fiberspec) add dco class to fiberspec role
  hieradata/role/fiberspec.yaml
  spec/classes/core/fiberspec_spec.rb
  spec/hosts/roles/fiberspec_spec.rb
Labels: enhancement

#1168 (profile::core::yum::lsst_ts_private) allow username to be Sensitive
  site/profile/manifests/core/yum/lsst_ts_private.pp
  spec/classes/core/yum/lsst_ts_private_spec.rb
Labels: bug

#1170 (Puppetfile) bump version of ccs_sal
  Puppetfile
Labels: bug, ccs

#1171 (Puppetfile) bump ccs_hcu version
  Puppetfile
Labels: bug, ccs

#1029 (role/dnscache) update dns forwarder ip
  hieradata/role/dnscache.yaml
Labels: enhancement

#1180 (cluster/comcam-ccs) no longer install old ccs releases
  hieradata/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#1186 (node/lsstcam-shutter01.cp) install ccs_hcu shutter utilities
  Puppetfile
  hieradata/node/lsstcam-shutter01.cp.lsst.org.yaml
Labels: enhancement, ccs

#1178 (profile::ccs::common) add some packages
  site/profile/data/common.yaml
Labels: enhancement, ccs
