Repository lsst-it/lsst-control, pull requests merged in 2024-08, with the labels that each got.

#1207 (site/cp/cluster/lsstcam-ccs) update clustershell groups
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1274 (profile::ccs::file_transfer) do not install idna_ssl on rhel9+
  site/profile/manifests/ccs/file_transfer.pp
Labels: enhancement, ccs

#1272 (cluster/{comcam,lsstcam}-ccs) add java17 settings for sal
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
Labels: bug, ccs

#1227 (profile::ccs::tomcat) miscellaneous small fixes
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/role/ccs-mcm.yaml
  site/profile/manifests/ccs/tomcat.pp
  spec/classes/ccs/tomcat_spec.rb
Labels: bug, ccs

#1276 (Puppetfile) bump lsst/daq to 2.4.0
  Puppetfile
Labels: enhancement

#1289 (renovate) tweaks to stop gha workflow failures on renovate PRs
  .github/workflows/commit_messages.yaml
  renovate.json
Labels: enhancement

#1290 (gha) fix "Commit Message Check" workflow skip of renovate PRs
  .github/workflows/commit_messages.yaml
Labels: bug

#1296 (spec) drop EL7 from default list of tested platforms
  metadata.json
Labels: enhancement

#1314 (gha) cancel long running workflows when branch is repushed
  .github/workflows/librarian_puppet.yaml
  .github/workflows/rake_checks.yaml
Labels: enhancement

#1315 (gha) fix librarian_puppet & rake_checks workflow canceling each other
  .github/workflows/librarian_puppet.yaml
  .github/workflows/rake_checks.yaml
Labels: bug

#1335 (Gemfile) rm outdated puppet-lint plugins
  Gemfile
Labels: enhancement

#1362 (gha) add canceling to all push-of-commit triggered workflows
  .github/workflows/block_merge_commits.yaml
  .github/workflows/commit_messages.yaml
  .github/workflows/markdownlint.yaml
  .github/workflows/pr_labels.yaml
  .github/workflows/shellcheck.yaml
  .github/workflows/yamllint.yaml
Labels: enhancement

#1363 (Puppetfile) rm puppetlabs/mount_providers; unused & deprecated
  Puppetfile
Labels: enhancement

#1273 (node/lsstcam-mcm.cp.lsst.org) add dds routes to node
  hieradata/node/lsstcam-mcm.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-mcm.cp.lsst.org_spec.rb
Labels: enhancement

#1367 (cluster/elqui) add rke2 role support
  hieradata/cluster/elqui/role/rke2.yaml
  spec/hosts/nodes/elqui01.cp.lsst.org_spec.rb
Labels: enhancement

#1368 (Puppetfile) rm fervid/snapd; unused
  Puppetfile
Labels: bug

#930 (node/hexrot) profile for hexrot
  Puppetfile
  hieradata/role/hexrot.yaml
  site/profile/manifests/ts/hexrot.pp
  spec/hosts/roles/hexrot_spec.rb
  spec/support/spec/nexusctio.rb
  spec/support/spec/ni_packages.rb
Labels: enhancement

#1375 (Puppetfile) bump puppet/firewalld to 5.0.0
  Puppetfile
Labels: enhancement

#1380 (Puppetfile) bump saz/resolv_conf to 7.0.0
  Puppetfile
Labels: enhancement

#1383 (Puppetfile) bump puppetlabs/tomcat to 7.2.0
  Puppetfile
Labels: enhancement

#1385 (role/rke) bump DEV client to v1.5.12
  hieradata/site/dev/role/rke.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/ayekan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1388 (role/perfsonar) add EL9 support
  hieradata/role/perfsonar.yaml
  site/profile/manifests/core/perfsonar.pp
  spec/hosts/roles/perfsonar_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#1389 (role/rke) bump TU rke client to v1.5.12
  hieradata/site/tu/role/rke.yaml
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.tu.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1395 (site/cp/cluster/lsstcam-ccs) enable mrtg
  Puppetfile
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
  site/profile/manifests/ccs/monitoring.pp
Labels: enhancement, ccs

#1398 (node/comcam-mcm.tu) fix tomcat rest.dbURL context parameter
  hieradata/node/comcam-mcm.tu.lsst.org.yaml
  site/profile/manifests/ccs/tomcat.pp
Labels: bug, ccs

#1396 (node/lsstcam-ccobwb.cp) fix duplicate uuid in nm::connections
  hieradata/node/lsstcam-ccobwb.cp.lsst.org.yaml
Labels: bug, ccs

#1400 (node/lsstcam-fb04.cp.lsst.org) provision host as EL9 & add test
  hieradata/node/lsstcam-fb04.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-fb04.cp.lsst.org_spec.rb
Labels: enhancement

#1401 (site/cp/cluster/comcam-ccs) enable mrtg
  hieradata/site/cp/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#1402 (role/rke) bump LS client to v1.5.12
  hieradata/site/ls/role/rke.yaml
  spec/hosts/nodes/antu01.ls.lsst.org_spec.rb
  spec/hosts/nodes/chango01.ls.lsst.org_spec.rb
  spec/hosts/nodes/gaw01.ls.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.ls.lsst.org_spec.rb
  spec/hosts/nodes/luan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.ls.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1403 (profile::core::lhnrouting) rm; was only used on el7
  hieradata/cluster/chonchon/role/rke.yaml
  hieradata/cluster/kueyen/role/rke.yaml
  hieradata/cluster/namkueyen/role/rke.yaml
  hieradata/cluster/ruka/role/rke.yaml
  hieradata/cluster/ruka/role/rke2.yaml
  hieradata/cluster/yagan/role/rke.yaml
  site/profile/manifests/core/lhnrouting.pp
  spec/classes/core/lhnrouting_spec.rb
Labels: enhancement

#1404 (common) update rke2 k8s to 1.18.12
  hieradata/common.yaml
  spec/hosts/nodes/elqui01.cp.lsst.org_spec.rb
  spec/hosts/nodes/elqui06.cp.lsst.org_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org-rke2_spec.rb
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
Labels: enhancement

#1407 (cluster/lsstcam-ccs) send rsyslog to fluentbit ayekan
  hieradata/cluster/lsstcam-ccs.yaml
  spec/hosts/nodes/lsstcam-dc01.cp.lsst.org_spec.rb
  spec/support/spec/lsstcam-rsyslog.rb
Labels: enhancement, ccs

#1408 (role/rke) bump CP client to v1.5.12
  hieradata/site/dev/role/rke.yaml
  hieradata/site/ls/role/rke.yaml
  hieradata/site/tu/role/rke.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
  spec/hosts/nodes/chonchon04.cp.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1405 (profile::core::hardware) enable amd_pstate driver on supported hw
  Puppetfile
  hieradata/role/rke.yaml
  site/profile/manifests/core/common.pp
  site/profile/manifests/core/hardware.pp
  site/profile/manifests/core/kernel.pp
  site/profile/manifests/util/kernel_param.pp
  spec/classes/core/kernel_spec.rb
  spec/defines/util/kernel_param_spec.rb
Labels: enhancement

#1411 (cluster/*) set ceph cluster tuned profile to latency-performance
  hieradata/cluster/antu.yaml
  hieradata/cluster/ayekan.yaml
  hieradata/cluster/chonchon.yaml
  hieradata/cluster/elqui.yaml
  hieradata/cluster/gaw.yaml
  hieradata/cluster/konkong.yaml
  hieradata/cluster/kueyen.yaml
  hieradata/cluster/luan.yaml
  hieradata/cluster/lukay.yaml
  hieradata/cluster/manke.yaml
  hieradata/cluster/namkueyen.yaml
  hieradata/cluster/pillan.yaml
  hieradata/cluster/ruka.yaml
  hieradata/cluster/yagan.yaml
  hieradata/cluster/yepun.yaml
  spec/hosts/nodes/antu01.ls.lsst.org_spec.rb
  spec/hosts/nodes/ayekan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
  spec/hosts/nodes/chonchon04.cp.lsst.org_spec.rb
  spec/hosts/nodes/elqui01.cp.lsst.org_spec.rb
  spec/hosts/nodes/gaw01.ls.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.ls.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/luan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org-rke2_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka04.dev.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
  spec/spec_helper.rb
  spec/support/spec/ceph.rb
Labels: enhancement

#1414 (cluster/{lsstcam,comcam}-ccs) add mrtg packet loss monitoring
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1415 (common) disable pquota by default
  hieradata/common.yaml
  site/profile/manifests/core/kernel/pquota.pp
  site/profile/manifests/util/kernel_param.pp
  spec/defines/util/kernel_param_spec.rb
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement, live-hosts

#1418 (node) remove and update duplicate uuids
  hieradata/node/comcam-dc01.cp.lsst.org.yaml
  hieradata/node/comcam-fp01.cp.lsst.org.yaml
  hieradata/node/lsstcam-daq-mgt.cp.lsst.org.yaml
Labels: enhancement

#1413 (role/hexrot) change versions and fix permissions
  hieradata/role/hexrot.yaml
  site/profile/manifests/ts/hexrot.pp
  spec/hosts/roles/hexrot_spec.rb
Labels: enhancement

#1420 (node/lsstcam-mcm.cp.lsst.org) update dds interface on node
  hieradata/node/lsstcam-mcm.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-mcm.cp.lsst.org_spec.rb
Labels: enhancement

#1417 (node/auxtel-mcm.cp, site/cp/role/ccs-mcm) configure ccs kafka brokers
  hieradata/node/auxtel-mcm.cp.lsst.org.yaml
  hieradata/site/cp/role/ccs-mcm.yaml
Labels: enhancement, ccs
