Repository lsst-it/lsst-control, pull requests merged in 2024-06, with the labels that each got.

#1189 (ccs) define more ccs services for lsstcam-cp hosts
  hieradata/node/lsstcam-shutter01.cp.lsst.org.yaml
  hieradata/node/lsstcam-shutter02.cp.lsst.org.yaml
Labels: enhancement, ccs

#1182 (node/lsstcam-dc*.cp) add services
  hieradata/node/lsstcam-dc01.cp.lsst.org.yaml
  hieradata/node/lsstcam-dc06.cp.lsst.org.yaml
  hieradata/site/cp/cluster/lsstcam-ccs/role/ccs-dc.yaml
Labels: enhancement, ccs

#1193 (rsyslog::config::actions) stop writing to /-/var/log/maillog
  hieradata/common.yaml
  spec/support/spec/rsyslog.rb
Labels: bug

#1196 (role/rke) rke bump dev to 1.5.9
  hieradata/role/rke.yaml
  hieradata/site/dev/role/rke.yaml
  hieradata/site/ls/role/rke.yaml
  hieradata/site/tu/role/rke.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/ayekan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1197 (site/ls) update ccs clusters for cycle 37
  hieradata/site/ls/cluster/auxtel-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1198 (role/rke) bump TU client to v1.5.9
  hieradata/site/tu/role/rke.yaml
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.tu.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1201 (cluster/antu) bump rke to 1.5.9
  hieradata/cluster/antu/role/rke.yaml
  spec/hosts/nodes/antu01.ls.lsst.org_spec.rb
Labels: enhancement, live-hosts

#1200 (site/cp/cluster/lsstcam-ccs) add clustershell groups
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1208 (node/lsstcam-dc02.cp) disable ccs image-handling service
  hieradata/node/lsstcam-dc02.cp.lsst.org.yaml
  hieradata/site/cp/cluster/lsstcam-ccs/role/ccs-dc.yaml
  spec/hosts/nodes/lsstcam-dc02.cp.lsst.org_spec.rb
Labels: enhancement, ccs

#1212 (Gemfile) pin facterdb < 2
  Gemfile
Labels: bug

#1195 (node/lsstcam-shutter02.cp.lsst.org) provision host as EL9
  hieradata/node/lsstcam-shutter02.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-shutter02.cp.lsst.org_spec.rb
Labels: enhancement

#1185 (node/comcam-lion03.cp) upgrade host to EL9
  hieradata/node/comcam-lion03.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-lion03.cp.lsst.org_spec.rb
Labels: enhancement

#1184 (node/comcam-lion01.cp) upgrade host to EL9
  hieradata/node/comcam-lion01.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-lion01.cp.lsst.org_spec.rb
Labels: enhancement

#1183 (node/comcam-lion02.cp) upgrade host to EL9
  hieradata/node/comcam-lion02.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-lion02.cp.lsst.org_spec.rb
Labels: enhancement

#1204 (node/lsstcam-fb02.cp) provision host as EL9
  Puppetfile
  hieradata/node/lsstcam-fb02.cp.lsst.org.yaml
  hieradata/role/ccs-hcu/osfamily/RedHat/major/9.yaml
  spec/hosts/nodes/lsstcam-fb02.cp.lsst.org_spec.rb
Labels: enhancement

#1211 (role/rke) bump LS client to v1.5.9
  hieradata/cluster/antu/role/rke.yaml
  hieradata/site/ls/role/rke.yaml
  spec/hosts/nodes/chango01.ls.lsst.org_spec.rb
  spec/hosts/nodes/gaw01.ls.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.ls.lsst.org_spec.rb
  spec/hosts/nodes/luan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.ls.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1145 (node/lsstcam-rebps.cp.lsst.org) deploy host as el9
  hieradata/node/lsstcam-rebps.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-rebps.cp.lsst.org_spec.rb
Labels: enhancement

#1218 (profile::ccs::profile_d) tweak default PATH
  site/profile/files/ccs/profile_d/lsst-ccs.sh
Labels: enhancement, ccs

#1149 (node/lsstcam-quad.cp.lsst.org) deploy host as el9
  hieradata/node/lsstcam-quad.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-quad.cp.lsst.org_spec.rb
Labels: enhancement

#1150 (node/lsstcam-vac.cp.lsst.org) deploy host as el9
  hieradata/node/lsstcam-vac.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-vac.cp.lsst.org_spec.rb
Labels: enhancement

#1158 (node/lsstcam-fcs.cp.lsst.org) deploy host as " EL7 "
  hieradata/node/lsstcam-fcs.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-fcs.cp.lsst.org_spec.rb
Labels: enhancement

#1173 (node/lsstcam-vw05.ls.lsst.org) provision host as EL9 & add test
  hieradata/node/lsstcam-vw05.ls.lsst.org.yaml
  spec/hosts/nodes/lsstcam-vw05.ls.lsst.org_spec.rb
Labels: enhancement

#1205 (node/comcam-fp01.cp) rebuild host as EL9
  hieradata/node/comcam-fp01.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-fp01.cp.lsst.org_spec.rb
Labels: enhancement

#1179 (node/lsstcam-vw02.cp.lsst.org) provision host EL9 & add test
  hieradata/node/lsstcam-vw02.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-vw02.cp.lsst.org_spec.rb
Labels: enhancement

#1214 (node/comcam-dc01.cp) add network configuration to support EL9
  hieradata/node/comcam-dc01.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-dc01.cp.lsst.org_spec.rb
Labels: enhancement

#1210 (node/comcam-mcm.cp) rebuild host as el9
  hieradata/node/comcam-mcm.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-mcm.cp.lsst.org_spec.rb
Labels: enhancement

#1169 (node/lsstcam-fb01.cp.lsst.org) deploy host as "el7"
  hieradata/node/lsstcam-fb01.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-fb01.cp.lsst.org_spec.rb
Labels: enhancement

#1217 (Puppetfile) bump ccs_hcu version
  Puppetfile
Labels: bug, ccs

#1215 (node/comcam-vs01.cp.lsst.org) provision host as EL9 & add test
  hieradata/node/comcam-vs01.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-vs01.cp.lsst.org_spec.rb
Labels: enhancement

#1174 (node/lsstcam-daq-mgt.cp) provision host EL8
  hieradata/node/lsstcam-daq-mgt.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-daq-mgt.cp.lsst.org_spec.rb
Labels: enhancement, daq

#1187 (node/lsstcam-aio01.cp.lsst.org) provision host EL9 & added network test
  hieradata/node/lsstcam-aio01.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-aio01.cp.lsst.org_spec.rb
Labels: enhancement

#1190 (node/lsstcam-aio02.cp.lsst.org) provision host as EL9 & add test
  hieradata/node/lsstcam-aio02.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-aio02.cp.lsst.org_spec.rb
Labels: enhancement

#1216 (node/lsstcam-fb03.cp.lsst.org) provision host as EL9 & add test
  hieradata/node/lsstcam-fb03.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-fb03.cp.lsst.org_spec.rb
Labels: enhancement

#1219 (node/foreman.cp) elqui dhcp pools for vlan1801 and vlan1802
  hieradata/node/foreman.cp.lsst.org.yaml
  spec/hosts/nodes/foreman.cp.lsst.org_spec.rb
Labels: enhancement

#1222 (node/comcam-daq-mgt.cp) rebuild host as EL8
  hieradata/node/comcam-daq-mgt.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-daq-mgt-cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-daq-mgt.cp.lsst.org_spec.rb
Labels: enhancement

#1223 (role/rke) bump CP client to v1.5.9
  hieradata/site/dev/role/rke.yaml
  hieradata/site/ls/role/rke.yaml
  hieradata/site/tu/role/rke.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1225 (cluster/{auxtel,comcam,lsstcam}-ccs) add ccs.InfluxDb property
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1226 (cluster/{auxtel,comcam,lsstcam}-ccs) remove ccs.InfluxDb property
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: bug, ccs

#1159 (node/lsstcam-ccobwb.cp.lsst.org) deploy host as el9
  hieradata/node/lsstcam-ccobwb.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-ccobwb.cp.lsst.org_spec.rb
Labels: enhancement

#1224 (node/comcam-mcm.cp) add dds routes to node
  hieradata/node/comcam-mcm.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-mcm.cp.lsst.org_spec.rb
Labels: enhancement

#1203 (node/lsstcam-vw04.cp.lsst.org) provision host as EL9 & add test
  hieradata/node/lsstcam-vw04.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-vw04.cp.lsst.org_spec.rb
Labels: enhancement

#1175 (node/lsstcam-pcs01.cp.lsst.org) provision host EL9 & add tests
  hieradata/node/lsstcam-pcs01.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-pcs01.cp.lsst.org_spec.rb
Labels: enhancement

#1221 (ccs) cycle 37 updates
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/cp/cluster/comcam-ccs.yaml
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
  hieradata/site/ls/cluster/auxtel-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1230 (cluster/lsstcam-ccs) install s3daemon for file transfer
  hieradata/cluster/lsstcam-ccs/role/ccs-dc.yaml
  hieradata/node/comcam-fp01.tu.lsst.org.yaml
  site/profile/manifests/ccs/file_transfer.pp
Labels: enhancement, ccs

#1232 (node/comcam-fp01.cp.lsst.org) add lhn test route to interface
  hieradata/node/comcam-fp01.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-fp01.cp.lsst.org_spec.rb
Labels: enhancement

#1234 (role/rke) bump kubectl to 1.28.10
  hieradata/role/rke.yaml
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1235 (role/rke) bump helm to 3.10.3
  hieradata/role/rke.yaml
  site/profile/manifests/core/helm.pp
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1231 (node/lsstcam-vw03.ls.lsst.org) provision host as EL9 & add test
  hieradata/node/lsstcam-vw03.ls.lsst.org.yaml
  spec/hosts/nodes/lsstcam-vw03.ls.lsst.org_spec.rb
Labels: enhancement

#1233 (node/lsstcam-pcs02.cp.lsst.org) provision host as EL9 & add test
  hieradata/node/lsstcam-pcs02.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-pcs02.cp.lsst.org_spec.rb
Labels: enhancement

#1162 (node/lsstcam-ccobtb.cp.lsst.org) Deploy host as EL9.
  hieradata/node/lsstcam-ccobtb.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-ccobtb.cp.lsst.org_spec.rb
Labels: enhancement

#1242 (profile::ccs::file_transfer) small updates for s3, oods
  hieradata/cluster/lsstcam-ccs.yaml
  site/profile/manifests/ccs/file_transfer.pp
Labels: enhancement, ccs

#1245 (cluster/comcam-ccs) set tomcat rest_url
  hieradata/cluster/comcam-ccs.yaml
Labels: bug, ccs

#1243 (node/lsstcam-fb01.cp.lsst.org) upgrade host to EL9 & add test
  hieradata/node/lsstcam-fb01.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-fb01.cp.lsst.org_spec.rb
Labels: enhancement

#1246 (node/lsstcam-fcs.cp.lsst.org) update host as EL9 & modify test
  hieradata/node/lsstcam-fcs.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-fcs.cp.lsst.org_spec.rb
Labels: enhancement
