Repository lsst-it/lsst-control, pull requests merged in 2024-03, with the labels that each got.

#1072 (tma-hcu01.cp) EL9 Deployment
  hieradata/node/tma-hcu01.cp.lsst.org.yaml
  spec/hosts/nodes/tma-hcu01.cp.lsst.org_spec.rb
Labels: enhancement

#1077 (node/comcam-fp01.tu.lsst.org) add lsst-daq interface
  hieradata/node/comcam-fp01.tu.lsst.org.yaml
  spec/hosts/nodes/comcam-fp01.tu.lsst.org_spec.rb
Labels: bug

#1078 (node/comcam-dc01.tu.lsst.org) add lsst-daq interface
  hieradata/node/comcam-dc01.tu.lsst.org.yaml
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
Labels: bug

#1076 (node/comcam-mcm.tu.lsst.org) EL9 deployment
  hieradata/node/comcam-mcm.tu.lsst.org.yaml
  spec/hosts/nodes/comcam-mcm.tu.lsst.org_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#1085 (node/comcam-dc01.tu.lsst.org) fix ens2f1 interface uuid
  hieradata/node/comcam-dc01.tu.lsst.org.yaml
Labels: bug

#1074 (site/cp) bump docker to 24.0.9
  hieradata/site/cp.yaml
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
Labels: enhancement

#1075 (role/rke) bump rke to 1.4.6 (to support k8s v1.25.9-rancher2-2)
  hieradata/cluster/rancher.yaml
  hieradata/cluster/yagan.yaml
  hieradata/cluster/yepun.yaml
  hieradata/role/rke.yaml
  hieradata/site/dev/role/rke.yaml
  hieradata/site/ls/role/rke.yaml
  hieradata/site/tu/role/rke.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1079 (node/auxtel-dc01.tu.lsst.org) enable dhcp on lsst-daq interface
  hieradata/node/auxtel-dc01.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
Labels: bug

#1081 (node/comcam-mcm.tu.lsst.org) rm ignore-auto-dns from manual interface
  hieradata/node/comcam-mcm.tu.lsst.org.yaml
  spec/hosts/nodes/comcam-mcm.tu.lsst.org_spec.rb
Labels: bug

#1083 (spec) fix misc spec issues for comcam-*.tu hosts
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-fp01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-mcm.tu.lsst.org_spec.rb
Labels: bug

#1080 (node/daq-mgt.tu.lsst.org) set lsst-daq int rx/tx ring to 4096
  hieradata/node/daq-mgt.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/daq-mgt.tu.lsst.org_spec.rb
Labels: bug

#1084 (node/lsstcam-daq-mgt.ls) rm ignore-auto-dns from manual interface(s)
  hieradata/node/lsstcam-daq-mgt.ls.lsst.org.yaml
  spec/hosts/nodes/lsstcam-daq-mgt.ls.lsst.org_spec.rb
Labels: bug

#1089 (ccs) install some new ccs releases
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1036 (role/atshcu) enable imanager
  Puppetfile
  hieradata/node/auxtel-hcu02.cp.lsst.org.yaml
  hieradata/role/atshcu.yaml
  site/profile/manifests/core/gpio.pp
Labels: enhancement, ccs

#1088 (site/dev) send syslog to opensearch.ayekan.dev.lsst.org
  hieradata/common.yaml
  hieradata/site/dev.yaml
  spec/hosts/roles/allsky_cam_spec.rb
  spec/hosts/roles/amor_spec.rb
  spec/hosts/roles/atsccs_spec.rb
  spec/hosts/roles/atsdaq_spec.rb
  spec/hosts/roles/atshcu_spec.rb
  spec/hosts/roles/auxtel_archiver_spec.rb
  spec/hosts/roles/auxtel_vent_gate_spec.rb
  spec/hosts/roles/bastion_spec.rb
  spec/hosts/roles/catchall_spec.rb
  spec/hosts/roles/ccs_dc_spec.rb
  spec/hosts/roles/ccs_desktop_spec.rb
  spec/hosts/roles/ccs_hcu_spec.rb
  spec/hosts/roles/ccs_mcm_spec.rb
  spec/hosts/roles/ccs_viswork_spec.rb
  spec/hosts/roles/comcam_archiver_spec.rb
  spec/hosts/roles/comcam_fp_spec.rb
  spec/hosts/roles/daq_mgt_spec.rb
  spec/hosts/roles/dco_spec.rb
  spec/hosts/roles/dimm_spec.rb
  spec/hosts/roles/dm_bastion_spec.rb
  spec/hosts/roles/dnscache_spec.rb
  spec/hosts/roles/docker_compose_spec.rb
  spec/hosts/roles/dtn_spec.rb
  spec/hosts/roles/ess_spec.rb
  spec/hosts/roles/foreman_spec.rb
  spec/hosts/roles/generic_spec.rb
  spec/hosts/roles/hexrot_spec.rb
  spec/hosts/roles/hvac_spec.rb
  spec/hosts/roles/hypervisor_spec.rb
  spec/hosts/roles/ipareplica_spec.rb
  spec/hosts/roles/it_ansible_spec.rb
  spec/hosts/roles/laserrpi_spec.rb
  spec/hosts/roles/logictimer_spec.rb
  spec/hosts/roles/m1m3_spec.rb
  spec/hosts/roles/m2_spec.rb
  spec/hosts/roles/nfsserver_spec.rb
  spec/hosts/roles/perfsonar_spec.rb
  spec/hosts/roles/puppetdb_spec.rb
  spec/hosts/roles/rke_spec.rb
  spec/hosts/roles/sal_dx_spec.rb
  spec/hosts/roles/tang_spec.rb
  spec/spec_helper.rb
  spec/support/spec/rsyslog.rb
Labels: enhancement

#1090 (node/auxtel-fp01.tu.lsst.org) EL9 upgrade
  hieradata/node/auxtel-fp01.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-fp01.tu.lsst.org_spec.rb
Labels: enhancement

#1091 (node/auxtel-mcm.tu.lsst.org) EL9 upgrade
  hieradata/node/auxtel-mcm.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-mcm.tu.lsst.org_spec.rb
Labels: enhancement

#1092 (WIP) auxtel-archiver.tu.lsst.org EL9 upgrade
  hieradata/node/auxtel-archiver.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-archiver.tu.lsst.org_spec.rb
Labels: enhancement

#1093 (profile::ccs::file_transfer) add option to install s3daemon
  hieradata/role/atsdaq.yaml
  hieradata/role/ccs-dc.yaml
  hieradata/role/comcam-fp.yaml
  site/profile/manifests/ccs/common.pp
  site/profile/manifests/ccs/file_transfer.pp
  site/profile/templates/ccs/file_transfer/s3daemon_envfile.epp
  site/profile/templates/ccs/service.epp
  spec/classes/ccs/file_transfer_spec.rb
  spec/fixtures/hieradata/common.yaml
Labels: enhancement, ccs

#1101 (site/dev) add `usehttps` flag for rsyslog -> opensearch
  hieradata/site/dev.yaml
  spec/support/spec/rsyslog.rb
Labels: bug

#1099 (node/tel-hw1.tu.lsst.org) EL9 upgrade
  hieradata/node/tel-hw1.tu.lsst.org.yaml
  spec/hosts/nodes/tel-hw1.tu.lsst.org_spec.rb
Labels: enhancement

#1100 (node/love1.tu.lsst.org) EL9 upgrade.
  hieradata/node/love1.tu.lsst.org.yaml
  spec/hosts/nodes/love1.tu.lsst.org_spec.rb
Labels: enhancement

#1103 (ccs_monit) change default mailserver to localhost
  Puppetfile
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#1106 (site/dev) send syslog/tls to rsyslog.fluent.ayekan.dev.lsst.org:5140
  hieradata/site/dev.yaml
  spec/support/spec/rsyslog.rb
Labels: enhancement

#1109 (Puppetfile) bump version of ccs_monit to 2.2.1
  Puppetfile
Labels: enhancement, ccs

#1097 (profile::ccs::file_transfer) handle /home/ccs-ipa being absent
  site/profile/manifests/ccs/file_transfer.pp
Labels: enhancement, ccs
