Repository lsst-it/lsst-control, pull requests merged in 2024-09, with the labels that each got.

#1424 (site/{cp,ls,tu}) add ccs_sal large file annex properties
  hieradata/site/cp.yaml
  hieradata/site/ls.yaml
  hieradata/site/tu.yaml
Labels: enhancement, ccs

#1426 (cluster/ruka) add ruka0[78] & drop rke1 support
  hieradata/cluster/ruka.yaml
  hieradata/cluster/ruka/role/rke.yaml
  hieradata/cluster/ruka/role/rke2agent.yaml
  hieradata/cluster/ruka/variant/c6420.yaml
  hieradata/node/test7.dev.lsst.org.yaml
  hieradata/node/test8.dev.lsst.org.yaml
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka04.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka07.dev.lsst.org_spec.rb
  spec/hosts/nodes/test7.dev.lsst.org_spec.rb
  spec/hosts/nodes/test8.dev.lsst.org_spec.rb
Labels: enhancement

#1425 (role/ess) add dco profile to ess role
  hieradata/role/ess.yaml
  spec/hosts/roles/ess_spec.rb
Labels: enhancement

#1428 (role/daq-mgt) Update DAQ to R5-V10.8
  hieradata/role/daq-mgt.yaml
Labels: enhancement, daq

#1410 (node/lsstcam-dc[1-10].cp.lsst.org) add lhn network to nodes
  hieradata/node/lsstcam-dc01.cp.lsst.org.yaml
  hieradata/node/lsstcam-dc02.cp.lsst.org.yaml
  hieradata/node/lsstcam-dc03.cp.lsst.org.yaml
  hieradata/node/lsstcam-dc04.cp.lsst.org.yaml
  hieradata/node/lsstcam-dc05.cp.lsst.org.yaml
  hieradata/node/lsstcam-dc06.cp.lsst.org.yaml
  hieradata/node/lsstcam-dc07.cp.lsst.org.yaml
  hieradata/node/lsstcam-dc08.cp.lsst.org.yaml
  hieradata/node/lsstcam-dc09.cp.lsst.org.yaml
  hieradata/node/lsstcam-dc10.cp.lsst.org.yaml
  hieradata/site/cp/variant/r6515.yaml
  spec/hosts/nodes/lsstcam-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc02.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc03.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc04.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc05.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc06.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc07.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc08.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc09.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc10.cp.lsst.org_spec.rb
Labels: enhancement

#1430 (profile::core::sysctl::lhn) add new parameters
  site/profile/data/common.yaml
  spec/classes/core/sysctl/lhn_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#1432 (node/test01-06.dev.lsst.org) cleanup test nodes for pukem
  hieradata/node/test1.dev.lsst.org.yaml
  hieradata/node/test2.dev.lsst.org.yaml
  hieradata/node/test3.dev.lsst.org.yaml
  hieradata/node/test4.dev.lsst.org.yaml
  hieradata/node/test5.dev.lsst.org.yaml
  hieradata/node/test6.dev.lsst.org.yaml
  spec/hosts/nodes/test1.dev.lsst.org_spec.rb
  spec/hosts/nodes/test2.dev.lsst.org_spec.rb
  spec/hosts/nodes/test3.dev.lsst.org_spec.rb
  spec/hosts/nodes/test4.dev.lsst.org_spec.rb
  spec/hosts/nodes/test5.dev.lsst.org_spec.rb
  spec/hosts/nodes/test6.dev.lsst.org_spec.rb
Labels: enhancement

#1431 (role/ccs-dc) add hosts entry for SLAC s3
  hieradata/role/ccs-dc.yaml
  spec/hosts/roles/ccs_dc_spec.rb
Labels: enhancement

#1434 (Puppetfile) bump theforeman/dhcp to 9.2.0
  Puppetfile
Labels: enhancement

#1433 (Puppetfile) bump theforeman/foreman to cf38cf0
  Puppetfile
Labels: enhancement

#1435 (Puppetfile) bump theforeman/puppet to 20.0.0
  Puppetfile
Labels: enhancement

#1437 (Puppetfile) bump theforeman/foreman_proxy to 90af64a
  Puppetfile
Labels: enhancement

#1436 (Puppetfile) bump theforeman/tftp to 9.1.0
  Puppetfile
Labels: enhancement

#1440 (Puppetfile) bump theforeman/foreman to 59ed5a5
  Puppetfile
Labels: enhancement

#1443 (Puppetfile) fork treydock/perfsonar to allow puppetlabs/firewall 8.x
  Puppetfile
Labels: enhancement

#1376 (Puppetfile) bump puppetdb, firewall, & postgresql
  Puppetfile
  hieradata/common.yaml
  hieradata/role/perfsonar.yaml
  hieradata/role/puppetdb.yaml
  hieradata/site/cp/role/tang.yaml
  hieradata/site/dev.yaml
  hieradata/site/dev/role/tang.yaml
  hieradata/site/ls.yaml
  hieradata/site/ls/role/tang.yaml
  hieradata/site/tu/role/tang.yaml
  spec/classes/core/firewall_spec.rb
  spec/hosts/roles/perfsonar_spec.rb
  spec/hosts/roles/puppetdb_spec.rb
  spec/hosts/roles/tang_spec.rb
  spec/support/spec/firewall.rb
Labels: enhancement

#1446 (Puppetfile) bump puppet/tang to 0.2.0
  Puppetfile
Labels: enhancement

#1447 (Puppetfile) bump puppet/lldpd to 6.1.0
  Puppetfile
Labels: enhancement

#1448 (Puppetfile) Update dependency puppet/systemd to v7
  .github/workflows/librarian_puppet.yaml
  Puppetfile
Labels: enhancement

#1451 (node/lsstcam-ccobtb.cp) add ccs service pap-pdu
  hieradata/node/lsstcam-ccobtb.cp.lsst.org.yaml
Labels: enhancement, ccs

#1456 (common) Add my ssh key to backup account
  hieradata/common.yaml
  spec/spec_helper.rb
Labels: enhancement

#1458 (Puppetfile) switch from camptocamp/augeas to puppet/augeas 2.0.0
  Puppetfile
Labels: enhancement

#1459 (cluster/{auxtel,comcam,lsstcam}-ccs) add new ccs releases
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1457 (Puppetfile) bump clustershell to an lsst-it fork
  Puppetfile
Labels: enhancement, ccs

#1460 (role/laserrpi) add dco profile to laserrpi role
  hieradata/role/laserrpi.yaml
  spec/hosts/roles/laserrpi_spec.rb
Labels: enhancement

#1237 (node/hexrot.cp.lsst.org) clean up network configuration
  hieradata/node/hexrot.cp.lsst.org.yaml
Labels: enhancement

#1371 (Puppetfile) update block/tailscale to 1.0.0
  Puppetfile
Labels: enhancement

#1463 (Puppetfile) bump ccin2p3/mit_krb5 to 2365ca8
  Puppetfile
Labels: enhancement

#1472 (node/lsstcam-archiver.cp.lsst.org) fwv
  hieradata/node/lsstcam-archiver.cp.lsst.org.yaml
  hieradata/role/nfsclient.yaml
  spec/hosts/nodes/lsstcam-archiver.cp.lsst.org_spec.rb
  spec/hosts/roles/nfsclient_spec.rb
Labels: enhancement

#1473 (node/azar03.cp.lsst.org) setup as tmp lsstcam-archiver.cp.lsst.org
  hieradata/node/azar03.cp.lsst.org.yaml
  hieradata/node/nfs1.cp.lsst.org.yaml
  hieradata/node/nfs3.cp.lsst.org.yaml
  hieradata/site/cp/role/nfsserver.yaml
  spec/hosts/nodes/azar03.cp.lsst.org_spec.rb
  spec/hosts/nodes/nfs1.cp.lsst.org_spec.rb
  spec/hosts/nodes/nfs3.cp.lsst.org_spec.rb
  spec/hosts/roles/nfsserver_spec.rb
Labels: enhancement

#1470 (*) rm telegraf; purge complete
  Gemfile
  Puppetfile
  hieradata/common.yaml
  hieradata/node/allsky2-cam.cp.lsst.org.yaml
  site/profile/manifests/core/common.pp
  spec/spec_helper.rb
  spec/support/spec/telegraf.rb
Labels: enhancement

#1480 (node/nfs3.cp.lsst.org) add comcam-archiver.cp.lsst.org export
  hieradata/node/nfs3.cp.lsst.org.yaml
  spec/hosts/nodes/nfs3.cp.lsst.org_spec.rb
Labels: enhancement
