Repository lsst-it/lsst-control, pull requests merged in 2024-11, with the labels that each got.

#1520 (cluster/elqui) misc tuning for ceph rgw
  hieradata/cluster/elqui.yaml
  hieradata/node/elqui06.cp.lsst.org.yaml
  hieradata/node/elqui07.cp.lsst.org.yaml
  hieradata/node/elqui08.cp.lsst.org.yaml
  spec/hosts/nodes/elqui01.cp.lsst.org_spec.rb
  spec/hosts/nodes/elqui06.cp.lsst.org_spec.rb
Labels: enhancement

#1429 (cluster/elqui) add lhn support
  hieradata/cluster/elqui.yaml
  hieradata/cluster/elqui/role/rke2agent.yaml
  hieradata/cluster/elqui/role/rke2server.yaml
  spec/hosts/nodes/elqui01.cp.lsst.org_spec.rb
  spec/hosts/nodes/elqui06.cp.lsst.org_spec.rb
Labels: enhancement

#1522 (cluster/yagan) add VLAN1702
  hieradata/cluster/yagan/variant/1114s.yaml
  hieradata/cluster/yagan/variant/1114s/subvariant/1.01.yaml
  hieradata/cluster/yagan/variant/1114s/subvariant/1.02.yaml
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
Labels: enhancement

#1526 (cluster/yagan) add CNI static plugin
  hieradata/cluster/kueyen.yaml
  hieradata/cluster/yagan.yaml
  hieradata/common.yaml
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
Labels: enhancement, help wanted

#1528 (site/tu/cluster/comcam-ccs) add s3dfrgw-comcam s3daemon instance
  hieradata/site/tu/cluster/comcam-ccs.yaml
  spec/fixtures/hieradata/site/tu/cluster/comcam-ccs.yaml
Labels: bug

#1529 (common) bump lsst-dm/s3daemon to sha-57e1aa9
  hieradata/common.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/support/spec/lsstcam.rb
Labels: bug

#1530 (node/foreman.cp) increase vlan1201|CDS-ARCH-DDS dhcp pool to 150 ips
  hieradata/node/foreman.cp.lsst.org.yaml
  spec/hosts/nodes/foreman.cp.lsst.org_spec.rb
Labels: enhancement

#1533 (cluster/auxtel-ccs) add new ccs release
  hieradata/cluster/auxtel-ccs.yaml
Labels: enhancement, ccs

#1508 (node/flat-fiberspecred.cp) deploy host as EL9
  hieradata/node/flat-fiberspecred.cp.lsst.org.yaml
  spec/hosts/nodes/flat-fiberspecred.cp.lsst.org_spec.rb
Labels: enhancement

#1542 (cluster/{comcam,lsstcam}-ccs) add new ccs release 39.2.0
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1534 (node/auxtel-daq-mgt.cp) add el9 network config and tests
  hieradata/node/auxtel-daq-mgt.cp.lsst.org.yaml
  spec/hosts/nodes/auxtel-daq-mgt-cp.lsst.org_spec.rb
Labels: enhancement

#1525 (node/auxtel-fp01.cp) add el9 network config & tests
  hieradata/node/auxtel-fp01.cp.lsst.org.yaml
  spec/hosts/nodes/auxtel-fp01.cp.lsst.org_spec.rb
Labels: enhancement

#1521 (node/auxtel-ill-control.cp) add el9 network config & tests
  hieradata/node/auxtel-ill-control.cp.lsst.org.yaml
  spec/hosts/nodes/auxtel-ill-control.cp.lsst.org_spec.rb
Labels: enhancement

#822 (role/ccs-mcm) merge role/atsccs into role/ccs-mcm
  hieradata/node/auxtel-mcm.cp.lsst.org.yaml
  hieradata/node/auxtel-mcm.ls.lsst.org.yaml
  hieradata/node/auxtel-mcm.tu.lsst.org.yaml
  hieradata/role/atsccs.yaml
  hieradata/role/ccs-mcm.yaml
  spec/hosts/nodes/auxtel-mcm.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-mcm.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-mcm.tu.lsst.org_spec.rb
  spec/hosts/roles/atsccs_spec.rb
  spec/hosts/roles/ccs_mcm_spec.rb
Labels: enhancement, ccs

#1547 (role/auxtel-fp) rename atsdaq role to auxtel-fp
  hieradata/role/auxtel-fp.yaml
  spec/hosts/nodes/auxtel-fp01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-fp01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-fp01.tu.lsst.org_spec.rb
  spec/hosts/roles/auxtel-fp_spec.rb
Labels: enhancement

#1549 (role/auxtel-hcu) rename atshcu role to auxtel-hcu
  hieradata/role/auxtel-hcu.yaml
  spec/hosts/nodes/auxtel-hcu02.cp.lsst.org_spec.rb
  spec/hosts/roles/auxtel-hcu_spec.rb
Labels: enhancement

#1550 (profile::pi::add_usb.pp) add serialusb class add class to role add test
  hieradata/role/ess.yaml
  hieradata/role/laserrpi.yaml
  site/profile/manifests/pi/add_usb.pp
  spec/hosts/roles/ess_spec.rb
  spec/hosts/roles/laserrpi_spec.rb
  spec/support/spec/add_usb.rb
Labels: enhancement

#1551 (node/auxtel-mcm.cp) add EL9 network configuration & tests
  hieradata/node/auxtel-mcm.cp.lsst.org.yaml
  spec/hosts/nodes/auxtel-mcm.cp.lsst.org_spec.rb
Labels: enhancement

#1543 (node/observer01.cp.lsst.org) provision host as EL9 & add test
  hieradata/node/observer01.cp.lsst.org.yaml
  spec/hosts/nodes/observer01.cp.lsst.org_spec.rb
Labels: enhancement

#1552 (node/auxtel-hcu01.cp.lsst.org) add el9 network & tests
  hieradata/node/auxtel-hcu01.cp.lsst.org.yaml
  spec/hosts/nodes/auxtel-hcu01.cp.lsst.org_spec.rb
Labels: enhancement

#1553 (auxtel-mcm.cp.lsst.org) manage mariadb package install
  hieradata/role/auxtelmcm.yaml
  site/profile/manifests/core/auxtelmcm.pp
  spec/classes/core/auxtelmcm_spec.rb
  spec/hosts/roles/auxtelmcm_spec.rb
  spec/support/spec/auxtelmcm.rb
Labels: enhancement
