Repository lsst-it/lsst-control, pull requests merged in 2024-07, with the labels that each got.

#1241 (node/comcam-vw01.cp) clean up network configuration
  hieradata/node/comcam-vw01.cp.lsst.org.yaml
Labels: enhancement

#1240 (node/comcam-ocsbr01.cp) clean up network configuration
  hieradata/node/comcam-ocsbr01.cp.lsst.org.yaml
Labels: enhancement

#1247 (node/bastion-lhn.cp.lsst.org) update host as EL9 & modify test
  hieradata/node/bastion-lhn.cp.lsst.org.yaml
  spec/hosts/nodes/bastion-lhn.cp.lsst.org_spec.rb
Labels: enhancement

#1239 (node/comcam-fwd02.cp) clean up network configuration
  hieradata/node/comcam-fwd02.cp.lsst.org.yaml
Labels: enhancement

#1238 (node/at-keener.cp) clean up network configuration
  hieradata/node/at-keener.cp.lsst.org.yaml
Labels: enhancement

#1250 (role/rke) bump TU client to v1.5.10
  hieradata/site/tu/role/rke.yaml
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.tu.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1251 (role/rke) bump LS client to v1.5.10
  hieradata/site/ls/role/rke.yaml
  spec/hosts/nodes/antu01.ls.lsst.org_spec.rb
  spec/hosts/nodes/chango01.ls.lsst.org_spec.rb
  spec/hosts/nodes/gaw01.ls.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.ls.lsst.org_spec.rb
  spec/hosts/nodes/luan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.ls.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1255 (common) add 139.229.181.0/27|vlan1801 to cpfde ipset
  hieradata/common.yaml
  spec/support/spec/ipset.rb
Labels: enhancement

#1252 (profile::core::k8snode) split out of profile::core::rke
  hieradata/cluster/chonchon.yaml
  hieradata/cluster/konkong.yaml
  hieradata/cluster/kueyen.yaml
  hieradata/cluster/manke.yaml
  hieradata/cluster/pillan.yaml
  hieradata/cluster/ruka.yaml
  hieradata/cluster/yagan.yaml
  hieradata/role/rke.yaml
  site/profile/manifests/core/k8snode.pp
  site/profile/manifests/core/rke.pp
  spec/classes/core/k8snode_spec.rb
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
  spec/spec_helper.rb
  spec/support/spec/k8snode.rb
  spec/support/spec/rke.rb
Labels: enhancement

#1257 (Puppetfile) bump ccs_software version to 2.3.0
  Puppetfile
Labels: enhancement, ccs

#1258 (role/rke) bump CP client to v1.5.10
  hieradata/site/dev/role/rke.yaml
  hieradata/site/ls/role/rke.yaml
  hieradata/site/tu/role/rke.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1260 (node/comcam-mcm.tu) add missing dds routes to el9 node
  hieradata/node/comcam-mcm.tu.lsst.org.yaml
  spec/hosts/nodes/comcam-mcm.tu.lsst.org_spec.rb
Labels: enhancement

#1259 (node/comcam-mcm.tu) switch sal from kafka back to dds
  Puppetfile
  hieradata/node/comcam-mcm.tu.lsst.org.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
Labels: bug, ccs

#1248 (Puppet) Remove sysstat package from hosts.
  Puppetfile
  site/profile/manifests/core/common.pp
Labels: enhancement

#1262 (node/love1.tu) add missing dds routes
  hieradata/node/love1.tu.lsst.org.yaml
  spec/hosts/nodes/love1.tu.lsst.org_spec.rb
Labels: enhancement

#1263 (node/tel-hw1.tu) add missing dds routes to node
  hieradata/node/tel-hw1.tu.lsst.org.yaml
  spec/hosts/nodes/tel-hw1.tu.lsst.org_spec.rb
Labels: enhancement

#1265 (role/htcondor) update environment vars
  hieradata/role/htcondor.yaml
  spec/hosts/roles/htcondor_spec.rb
Labels: enhancement

#1266 (site/tu/cluster/comcam-ccs) fix JAVA_HOME setting for DDS
  Puppetfile
  hieradata/site/tu/cluster/comcam-ccs.yaml
Labels: bug, ccs

#1268 (role/daq-mgt) Update DAQ to R5-V10.2
  hieradata/role/daq-mgt.yaml
Labels: enhancement, daq

#1269 (cluster/{auxtel,comcam,lsstcam}-ccs) add new ccs releases
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1261 (node/auxtel-mcm.tu) add missing dds routes to node
  hieradata/node/auxtel-mcm.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-mcm.tu.lsst.org_spec.rb
Labels: enhancement

#1271 (node/lsstcam-vw03.cp.lsst.org) upgrade host as EL9 & add test
  hieradata/node/lsstcam-vw03.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-vw03.cp.lsst.org_spec.rb
Labels: enhancement

#1236 (node/comcam-fp01.cp) add hosts entry for SLAC s3
  hieradata/node/comcam-fp01.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-fp01.cp.lsst.org_spec.rb
Labels: enhancement

#1275 (node/pathfinder-hcu01.cp.lsst.org) upgrade host as EL9 & add test
  hieradata/node/pathfinder-hcu01.cp.lsst.org.yaml
  spec/hosts/nodes/pathfinder-hcu01.cp.lsst.org_spec.rb
Labels: enhancement

#1244 (role/rke2) fwv
  Puppetfile
  hieradata/cluster/ruka/role/rke2.yaml
  hieradata/common.yaml
  hieradata/role/rke2.yaml
  site/profile/manifests/core/kubecompletion.pp
  spec/hosts/nodes/ruka01.dev.lsst.org-rke2_spec.rb
  spec/hosts/roles/rke2_spec.rb
Labels: enhancement

#1253 (cluster/elqui) fwv
  hieradata/cluster/elqui.yaml
  spec/hosts/nodes/elqui01.cp.lsst.org_spec.rb
Labels: enhancement

#1256 (spec) mv foreman & 'foreman generic' example groups to support file
  spec/spec_helper.rb
  spec/support/spec/foreman.rb
Labels: enhancement

#1228 (role/{atsccs,ccs-dc,comcam-fp}) apply basic lhn transfer tuning
  hieradata/role/atsccs.yaml
  hieradata/role/ccs-dc.yaml
  hieradata/role/comcam-fp.yaml
  spec/hosts/roles/atsccs_spec.rb
  spec/hosts/roles/ccs_dc_spec.rb
  spec/hosts/roles/comcam_fp_spec.rb
Labels: enhancement
