Repository lsst-it/lsst-control, pull requests merged in 2025-06, with the labels that each got.

#1786 (site/dev) Add Kueyen Fluent Bit forward target in Puppet config
  spec/support/spec/rsyslog.rb
Labels: enhancement

#1788 (tv-desktop01.cp.lsst.org) Add host config and tests
  hieradata/node/tv-desktop01.cp.lsst.org.yaml
  spec/hosts/nodes/tv-desktop01.cp.lsst.org_spec.rb
Labels: enhancement

#1780 (node/hvac01.cp) remove el7 host from repo
  hieradata/node/hvac01.cp.lsst.org.yaml
  hieradata/role/hvac.yaml
  spec/hosts/roles/hvac_spec.rb
Labels: enhancement

#1798 (role/daq-mgt) Update DAQ to R5-V13.9
  hieradata/role/daq-mgt.yaml
Labels: enhancement, daq

#1787 (cluster/rancher) migrate rancher.ls RKE2
  hieradata/site/ls/cluster/rancher.yaml
  hieradata/site/ls/cluster/rancher/role/rke.yaml
  spec/hosts/nodes/rancher01.ls.lsst.org_spec.rb
Labels: enhancement

#1810 (common) bump s3nd to v1.5.1
  hieradata/common.yaml
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/support/spec/lsstcam.rb
Labels: enhancement

#1808 (role/perfsonar) update toolkit config
  hieradata/role/perfsonar.yaml
  spec/hosts/roles/perfsonar_spec.rb
Labels: enhancement

#1813 (common) bump s3nd to v1.5.2
  hieradata/common.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/support/spec/lsstcam.rb
Labels: bug
