Repository lsst-it/lsst-control, pull requests merged in 2025-04, with the labels that each got.

#1673 (Puppetfile) Update puppetfile with current version of helm-binary
  Puppetfile
Labels: enhancement

#1678 (Puppetfile) Update Puppetfile to our branch of Docker
  Puppetfile
Labels: enhancement

#1694 (site/cp/cluster/{auxtel,comcam,lsstcam}-ccs) add ccs 41.0.0
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/cp/cluster/comcam-ccs.yaml
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1696 (site/cp/cluster/auxtel-ccs.yaml) fix typo in recent
  hieradata/site/cp/cluster/auxtel-ccs.yaml
Labels: bug, ccs

#1695 (role/hexrot) bump mtdomegui 0.4.7 and mtdomecom 0.2.6
  hieradata/role/hexrot.yaml
  spec/hosts/roles/hexrot_spec.rb
Labels: enhancement

#1699 (observer02.ls.lsst.org) Add network config and test
  hieradata/node/observer02.ls.lsst.org.yaml
  spec/hosts/nodes/observer02.ls.lsst.org_spec.rb
Labels: enhancement

#1701 (role/hexrot) bump mtdomegui and mtdomecom version
  hieradata/role/hexrot.yaml
  spec/hosts/roles/hexrot_spec.rb
Labels: enhancement

#1703 Revert "Update dependency puppet/rsyslog to v7.3.0"
  Puppetfile
Labels: bug

#1708 (role/daq-mgt) Update DAQ to R5-V13.6
  hieradata/role/daq-mgt.yaml
Labels: enhancement, daq

#1674 (cluster/rancher) bump rke2 version
  hieradata/cluster/ruka.yaml
  hieradata/site/dev/cluster/rancher.yaml
  hieradata/site/dev/role/rke2agent.yaml
  hieradata/site/dev/role/rke2server.yaml
  spec/hosts/nodes/rancher01.dev.lsst.org_spec.rb
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
Labels: enhancement

#1704 (role/hexrot) mayor bump python 3.12 and conda packages
  hieradata/role/hexrot.yaml
  site/profile/manifests/ts/hexrot.pp
  spec/hosts/roles/hexrot_spec.rb
Labels: enhancement

#1715 (cluster/{auxtel,comcam,lsstcam}-ccs) add new ccs release 41.0.1
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/cp/cluster/comcam-ccs.yaml
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1720 (node/*) remove the powertop
  hieradata/node/lsstcam-vw01.cp.lsst.org.yaml
  hieradata/node/lsstcam-vw02.cp.lsst.org.yaml
  hieradata/node/lsstcam-vw04.cp.lsst.org.yaml
  hieradata/node/observer01.ls.lsst.org.yaml
  hieradata/node/observer02.ls.lsst.org.yaml
  spec/hosts/nodes/lsstcam-vw01.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-vw02.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-vw04.cp.lsst.org_spec.rb
  spec/hosts/nodes/observer01.ls.lsst.org_spec.rb
  spec/hosts/nodes/observer02.ls.lsst.org_spec.rb
Labels: bug

#1697 (luan) RKE1 -> RKE2 migration
  hieradata/cluster/luan.yaml
  hieradata/cluster/luan/role/rke2agent.yaml
  hieradata/cluster/luan/role/rke2server.yaml
  spec/hosts/nodes/luan01.ls.lsst.org_spec.rb
Labels: enhancement

#1702 (cluster/ayekan) convert rke[1] -> rke2
  hieradata/cluster/ayekan.yaml
  hieradata/cluster/ayekan/role/rke2server.yaml
  hieradata/common.yaml
  hieradata/node/foreman.dev.lsst.org.yaml
  hieradata/node/foreman.ls.lsst.org.yaml
  spec/hosts/nodes/ayekan01.dev.lsst.org_spec.rb
  spec/hosts/nodes/foreman.dev.lsst.org_spec.rb
  spec/hosts/nodes/foreman.ls.lsst.org_spec.rb
  spec/support/spec/ipset.rb
Labels: enhancement, live-hosts

#1722 (Puppetfile) Bump all dependencies
  Puppetfile
Labels: enhancement

#1725 (Puppetfile) Fix r10k and docker ref number
  Puppetfile
Labels: bug

#1727 (rke2) bump dev rke2 k8s 1.31.7~rke2r1
  hieradata/site/dev/role/rke2agent.yaml
  hieradata/site/dev/role/rke2server.yaml
  spec/hosts/nodes/ayekan01.dev.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka04.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka07.dev.lsst.org_spec.rb
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
Labels: enhancement

#1649 (pukem) provision cluster with rke2
  hieradata/cluster/pukem.yaml
  hieradata/cluster/pukem/role/rke2agent.yaml
  hieradata/cluster/pukem/role/rke2server.yaml
  hieradata/cluster/pukem/variant/R730.yaml
  hieradata/cluster/pukem/variant/c6420.yaml
  spec/hosts/nodes/pukem01.dev.lsst.org_spec.rb
  spec/hosts/nodes/pukem04.dev.lsst.org_spec.rb
Labels: enhancement

#1729 (role/rke/rke2) bump LS client to v1.7.6 / rke2 k8s 1.31.7~rke2r1
  hieradata/site/ls/role/rke.yaml
  hieradata/site/ls/role/rke2agent.yaml
  hieradata/site/ls/role/rke2server.yaml
  hieradata/site/tu/role/rke2agent.yaml
  hieradata/site/tu/role/rke2server.yaml
  site/profile/manifests/core/rke.pp
  spec/hosts/nodes/antu01.ls.lsst.org_spec.rb
  spec/hosts/nodes/chango01.ls.lsst.org_spec.rb
  spec/hosts/nodes/gaw01.ls.lsst.org_spec.rb
  spec/hosts/nodes/konkong01.ls.lsst.org_spec.rb
  spec/hosts/nodes/luan01.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.ls.lsst.org_spec.rb
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1731 (cluster/ayekan) increase rke2 max pods to 250
  hieradata/cluster/ayekan/role/rke2server.yaml
  spec/hosts/nodes/ayekan01.dev.lsst.org_spec.rb
Labels: enhancement

#1732 (cluster/manke) increase rke2 max pods to 250
  hieradata/cluster/manke/role/rke2agent.yaml
  hieradata/cluster/manke/role/rke2server.yaml
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
Labels: enhancement
