Repository lsst-it/lsst-control, pull requests merged in 2025-05, with the labels that each got.

#1735 (cluster/chonchon) remove chonchon config/test
  hieradata/cluster/chonchon.yaml
  hieradata/cluster/chonchon/role/rke.yaml
  hieradata/cluster/chonchon/variant/1115hs.yaml
  hieradata/cluster/chonchon/variant/R730.yaml
  spec/hosts/nodes/chonchon01.cp.lsst.org_spec.rb
  spec/hosts/nodes/chonchon04.cp.lsst.org_spec.rb
Labels: enhancement

#1738 (site/common) bump docker version
  hieradata/site/cp.yaml
  hieradata/site/dev.yaml
  hieradata/site/ls.yaml
  hieradata/site/ls/role/rke.yaml
  hieradata/site/tu/role/rke.yaml
  site/profile/data/common.yaml
  spec/classes/core/docker_spec.rb
Labels: enhancement

#1737 (role/daq-mgt) Update DAQ to R5-V13.7
  hieradata/role/daq-mgt.yaml
Labels: enhancement, daq

#1739 (role/daq-mgt) Update DAQ to R5-V13.8
  hieradata/role/daq-mgt.yaml
Labels: enhancement, daq

#1736 (role/rke/rke2) bump CP rke client v1.7.6 and rke2 k8s v1.31.7
  hieradata/common.yaml
  hieradata/site/dev/role/rke2agent.yaml
  hieradata/site/dev/role/rke2server.yaml
  hieradata/site/ls/role/rke.yaml
  hieradata/site/ls/role/rke2agent.yaml
  hieradata/site/ls/role/rke2server.yaml
  hieradata/site/tu/role/rke2agent.yaml
  hieradata/site/tu/role/rke2server.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/elqui01.cp.lsst.org_spec.rb
  spec/hosts/nodes/elqui06.cp.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/kueyen04.dev.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/namkueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.cp.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.tu.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1743 (cluster/{auxtel,comcam,lsstcam}-ccs) add new ccs release 41.0.2
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1740 (role/hexrot) bump ts-m2gui to v1.1.6
  hieradata/role/hexrot.yaml
  spec/hosts/roles/hexrot_spec.rb
Labels: enhancement

#1746 (cluster/rancher) migrate rancher.tu RKE2
  hieradata/site/tu/cluster/rancher.yaml
  spec/hosts/nodes/rancher01.tu.lsst.org_spec.rb
Labels: enhancement

#1741 (cluster/namkueyen) remove cluster config
  hieradata/cluster/namkueyen.yaml
  hieradata/cluster/namkueyen/role/rke.yaml
Labels: enhancement

#1749 (profile::ccs::file_transfer) script updates
  hieradata/cluster/lsstcam-ccs.yaml
  site/profile/manifests/ccs/file_transfer.pp
Labels: enhancement, ccs

#1756 (nodes/lsstcam-archiver.ls) rm; reprovisioned as manke11.ls
  spec/hosts/nodes/lsstcam-archiver.ls.lsst.org_spec.rb
Labels: enhancement

#1757 (node/bastion1.cp) remove host from repo
  hieradata/node/bastion1.cp.lsst.org.yaml
  spec/hosts/nodes/bastion1.cp.lsst.org_spec.rb
Labels: enhancement

#1762 (profile::ccs::file_transfer) add new script
  site/profile/manifests/ccs/file_transfer.pp
Labels: enhancement, ccs

#1761 (common) Update dependency lsst/s3daemon to v2
  Puppetfile
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/cp/cluster/comcam-ccs.yaml
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
  hieradata/site/ls/cluster/auxtel-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/support/spec/lsstcam.rb
Labels: enhancement

#1744 (role/comcam-archiver) rm
  hieradata/node/comcam-archiver.cp.lsst.org.yaml
  hieradata/node/comcam-archiver.tu.lsst.org.yaml
  hieradata/role/comcam-archiver.yaml
  site/profile/data/common.yaml
  site/profile/manifests/archive/data/comcam.pp
  spec/classes/archive/data/comcam_spec.rb
  spec/hosts/nodes/comcam-archiver.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-archiver.tu.lsst.org_spec.rb
  spec/hosts/roles/comcam_archiver_spec.rb
Labels: enhancement

#1764 (node/comcam-archiver.cp) remove reamaining conf
  hieradata/node/comcam-archiver.cp.lsst.org.yaml
  spec/hosts/nodes/comcam-archiver.cp.lsst.org_spec.rb
Labels: enhancement

#1758 (node/nfs1.cp.lsst.org) clean up host from summit infrastructure
  hieradata/node/nfs1.cp.lsst.org.yaml
  site/profile/data/common.yaml
  spec/classes/nfs/csc_spec.rb
  spec/hosts/nodes/nfs1.cp.lsst.org_spec.rb
Labels: enhancement

#1751 (Puppetfile) Switch puppet-dhcp to official
  Puppetfile
Labels: enhancement

#1763 (site/*/cluster/*-ccs) deploy s3nd service
  hieradata/common.yaml
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/cp/cluster/comcam-ccs.yaml
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
  hieradata/site/ls/cluster/auxtel-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
  spec/fixtures/hieradata/site/cp/cluster/auxtel-ccs.yaml
  spec/fixtures/hieradata/site/cp/cluster/comcam-ccs.yaml
  spec/fixtures/hieradata/site/cp/cluster/lsstcam-ccs.yaml
  spec/fixtures/hieradata/site/ls/cluster/auxtel-ccs.yaml
  spec/fixtures/hieradata/site/ls/cluster/lsstcam-ccs.yaml
  spec/fixtures/hieradata/site/tu/cluster/auxtel-ccs.yaml
  spec/fixtures/hieradata/site/tu/cluster/comcam-ccs.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/support/spec/lsstcam.rb
Labels: enhancement

#1767 (rke2) bump tuc rke2 k8s 1.31.8~rke2r1
  hieradata/site/tu/role/rke2agent.yaml
  hieradata/site/tu/role/rke2server.yaml
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.tu.lsst.org_spec.rb
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
Labels: enhancement

#1768 (common) Replace gseriche ssh key to backup account
  hieradata/common.yaml
Labels: enhancement

#1770 (cluster/{auxtel,comcam,lsstcam}-ccs) add new ccs release 41.0.3
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1775 (common) bump s3nd to 1.0.1
  hieradata/common.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/support/spec/lsstcam.rb
Labels: enhancement

#1776 (common) mount /data in all s3daemon|s3nd containers
  Puppetfile
  hieradata/common.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/support/spec/lsstcam.rb
Labels: enhancement
