Repository lsst-it/lsst-control, pull requests merged in 2025-03, with the labels that each got.

#1655 (profile::core::rucio) whitespace fix
  site/profile/manifests/core/rucio.pp
Labels: bug

#1654 (site/cp) move and rename the ccs pdu service
  hieradata/node/lsstcam-ccobtb.cp.lsst.org.yaml
  hieradata/node/lsstcam-mcm.cp.lsst.org.yaml
Labels: enhancement, ccs

#1656 (role/daq-mgt) Update DAQ to R5-V13.2
  hieradata/role/daq-mgt.yaml
Labels: enhancement, daq

#1659 (role/fiberspec.yaml) add docker profile
  hieradata/role/fiberspec.yaml
  spec/hosts/roles/fiberspec_spec.rb
Labels: enhancement

#1653 (node/yagan1[56].cp) add local-storage: "true" node label
  hieradata/node/yagan15.cp.lsst.org.yaml
  hieradata/node/yagan16.cp.lsst.org.yaml
Labels: enhancement

#1660 (common/firewall) add antu and set port for node_exporter
  hieradata/common.yaml
  hieradata/site/cp.yaml
  hieradata/site/dev.yaml
  hieradata/site/ls.yaml
  spec/support/spec/firewall.rb
  spec/support/spec/ipset.rb
Labels: enhancement

#1661 (role/daq-mgt) Update to DAQ R5-V13.4
  hieradata/role/daq-mgt.yaml
Labels: enhancement, daq

#1662 (cluster/ruka) bump rke2 to v1.31.6+rke2r1
  hieradata/cluster/ruka.yaml
  spec/hosts/nodes/ruka01.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka04.dev.lsst.org_spec.rb
  spec/hosts/nodes/ruka07.dev.lsst.org_spec.rb
Labels: enhancement

#1665 (site/{cp/ls}/cluster/{auxtel,comcam,lsstcam}-ccs) add ccs 40.0.3
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/cp/cluster/comcam-ccs.yaml
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
  hieradata/site/ls/cluster/auxtel-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1668 (role/rke2) set dhcp to service_only on multus clusters
  hieradata/cluster/konkong/role/rke2agent.yaml
  hieradata/cluster/konkong/role/rke2server.yaml
  hieradata/cluster/manke/role/rke2agent.yaml
  hieradata/cluster/manke/role/rke2server.yaml
  hieradata/cluster/pillan/role/rke2agent.yaml
  hieradata/cluster/pillan/role/rke2server.yaml
  hieradata/cluster/yagan/role/rke2agent.yaml
  hieradata/cluster/yagan/role/rke2server.yaml
  spec/hosts/nodes/konkong01.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
Labels: bug

#1663 (profile::ccs::tomcat) add efdCredentials
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
  hieradata/node/auxtel-mcm.cp.lsst.org.yaml
  hieradata/role/auxtelmcm.yaml
  site/profile/manifests/ccs/tomcat.pp
  site/profile/templates/ccs/tomcat/efdCredentials.properties.epp
Labels: enhancement, ccs

#1669 (role/daq-mgt) Update Camera to DAQ R5-V13.5
  hieradata/role/daq-mgt.yaml
Labels: enhancement, daq

#1671 (site/cp/role/ccs-dc) adjust /data usage warning threshold
  Puppetfile
  hieradata/site/cp/role/ccs-dc.yaml
Labels: enhancement, ccs

#1670 (node/{auxtel,comcam,lsstcam}-mcm.cp) add monit hosts
  hieradata/node/auxtel-mcm.cp.lsst.org.yaml
  hieradata/node/comcam-fp01.cp.lsst.org.yaml
  hieradata/node/comcam-mcm.cp.lsst.org.yaml
  hieradata/node/lsstcam-mcm.cp.lsst.org.yaml
Labels: enhancement, ccs

#1672 (role/hexrot) bump mtdomegui and mtdomecom versions
  hieradata/role/hexrot.yaml
  spec/hosts/roles/hexrot_spec.rb
Labels: enhancement
