Repository lsst-it/lsst-control, pull requests merged in 2025-07, with the labels that each got.

#1817 (cluster/{auxtel,comcam,lsstcam}-ccs) add new ccs release 41.0.5
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1818 (node/tel-hw1.tu) update nfs mount point
  hieradata/node/tel-hw1.tu.lsst.org.yaml
  spec/hosts/nodes/tel-hw1.tu.lsst.org_spec.rb
Labels: enhancement

#1822 (site/cp/cluster/lsstcam-ccs) change sdfembs3-lsstcam-s3nd timeout to 4s
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
  spec/support/spec/lsstcam.rb
Labels: enhancement

#1824 (common) bump s3nd to v1.6.0
  hieradata/common.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/support/spec/lsstcam.rb
Labels: enhancement

#1779 (role/rke/rke2) bump CP rke client v1.7.7 and rke2 k8s v1.31.8
  hieradata/common.yaml
  hieradata/site/dev/role/rke2agent.yaml
  hieradata/site/dev/role/rke2server.yaml
  hieradata/site/ls/role/rke.yaml
  hieradata/site/ls/role/rke2agent.yaml
  hieradata/site/ls/role/rke2server.yaml
  hieradata/site/tu/role/rke2agent.yaml
  hieradata/site/tu/role/rke2server.yaml
  site/profile/manifests/core/rke.pp
  spec/classes/core/rke_spec.rb
  spec/hosts/nodes/elqui01.cp.lsst.org_spec.rb
  spec/hosts/nodes/elqui06.cp.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/kueyen04.dev.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/rancher01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
  spec/hosts/roles/rke_spec.rb
Labels: enhancement

#1754 (common) bump docker version to 25.0.3
  site/profile/data/common.yaml
  site/profile/data/osfamily/RedHat/major/8.yaml
  site/profile/data/osfamily/RedHat/major/9.yaml
  spec/classes/core/docker_spec.rb
  spec/hosts/nodes/antu01.ls.lsst.org_spec.rb
  spec/hosts/nodes/kueyen01.dev.lsst.org_spec.rb
  spec/hosts/nodes/lukay01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yepun01.cp.lsst.org_spec.rb
  spec/support/spec/docker.rb
Labels: enhancement

#1827 (site/cp/cluster/auxtel-ccs) change s3 endpoint s3dfrgw -> sdfembs3
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  spec/fixtures/hieradata/site/cp/cluster/auxtel-ccs.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
Labels: enhancement

#1825 (nodes/observer01) remove powertop from observer workstation
  hieradata/node/observer01.cp.lsst.org.yaml
  spec/hosts/nodes/observer01.cp.lsst.org_spec.rb
Labels: enhancement

#1830 (observer01.cp.lsst.org) Update network interface name
  hieradata/node/observer01.cp.lsst.org.yaml
  spec/hosts/nodes/observer01.cp.lsst.org_spec.rb
Labels: bug

#1828 (*) mv s3nd {auxtel,comcam}-dc01 -> {auxtel,comcam}-fp01; rm s3daemon test instances
  Puppetfile
  hieradata/cluster/lsstcam-ccs/role/ccs-dc.yaml
  hieradata/common.yaml
  hieradata/role/auxtel-fp.yaml
  hieradata/role/ccs-dc.yaml
  hieradata/role/comcam-fp.yaml
  hieradata/site/cp/cluster/auxtel-ccs.yaml
  hieradata/site/cp/cluster/comcam-ccs.yaml
  hieradata/site/cp/cluster/lsstcam-ccs.yaml
  hieradata/site/ls/cluster/auxtel-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
  hieradata/site/tu/cluster/auxtel-ccs.yaml
  hieradata/site/tu/cluster/comcam-ccs.yaml
  spec/fixtures/hieradata/common.yaml
  spec/fixtures/hieradata/site/cp/cluster/auxtel-ccs.yaml
  spec/fixtures/hieradata/site/cp/cluster/comcam-ccs.yaml
  spec/fixtures/hieradata/site/cp/cluster/lsstcam-ccs.yaml
  spec/fixtures/hieradata/site/ls/cluster/auxtel-ccs.yaml
  spec/fixtures/hieradata/site/ls/cluster/lsstcam-ccs.yaml
  spec/fixtures/hieradata/site/tu/cluster/auxtel-ccs.yaml
  spec/fixtures/hieradata/site/tu/cluster/comcam-ccs.yaml
  spec/hosts/nodes/auxtel-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-fp01.cp.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-fp01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-fp01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-fp01.cp.lsst.org_spec.rb
  spec/hosts/nodes/comcam-fp01.tu.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
  spec/hosts/roles/auxtel-fp_spec.rb
  spec/hosts/roles/ccs-dc_spec.rb
  spec/hosts/roles/comcam-fp_spec.rb
  spec/support/spec/lsstcam.rb
  spec/support/spec/s3daemon.rb
  spec/support/spec/s3nd.rb
Labels: enhancement

#1833 (node/auxtel-fp01.ls) mv /ccs-data -> /data
  hieradata/node/auxtel-dc01.ls.lsst.org.yaml
  hieradata/node/auxtel-fp01.ls.lsst.org.yaml
  spec/hosts/nodes/auxtel-dc01.ls.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-fp01.ls.lsst.org_spec.rb
Labels: enhancement

#1835 (node/{auxtel,comcam}-fp01.tu) mv /ccs-data -> /data
  hieradata/node/auxtel-dc01.tu.lsst.org.yaml
  hieradata/node/auxtel-fp01.tu.lsst.org.yaml
  hieradata/node/comcam-dc01.tu.lsst.org.yaml
  hieradata/node/comcam-fp01.tu.lsst.org.yaml
  spec/hosts/nodes/auxtel-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/auxtel-fp01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-dc01.tu.lsst.org_spec.rb
  spec/hosts/nodes/comcam-fp01.tu.lsst.org_spec.rb
Labels: enhancement

#1837 (node/auxtel-fp01.tu) fix nfs export to auxtel-dc01.tu
  hieradata/node/auxtel-fp01.tu.lsst.org.yaml
Labels: enhancement

#1829 (observer.ls.lsst.org) remove observer.ls
  hieradata/node/observer01.ls.lsst.org.yaml
  spec/hosts/nodes/observer01.ls.lsst.org_spec.rb
Labels: enhancement

#1843 (site/ls) bump s3nd to 1.7.0
  hieradata/site/ls.yaml
  hieradata/site/ls/cluster/auxtel-ccs.yaml
  hieradata/site/ls/cluster/lsstcam-ccs.yaml
  spec/hosts/nodes/auxtel-fp01.ls.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-dc01.ls.lsst.org_spec.rb
Labels: enhancement

#1845 (node/tel-hw1.ls) add nfs mount
  hieradata/node/tel-hw1.ls.lsst.org.yaml
  spec/hosts/nodes/tel-hw1.ls.lsst.org_spec.rb
Labels: enhancement
