Repository lsst-it/lsst-control, pull requests merged in 2025-02, with the labels that each got.

#1571 (site/ls) ccs_sal replace dds with kafka
  Puppetfile
  hieradata/site/ls.yaml
  spec/hosts/nodes/auxtel-mcm.ls.lsst.org_spec.rb
Labels: enhancement, ccs

#1622 (site/cp) switch CCS SAL hosts from DDS to Kafka
  hieradata/site/cp.yaml
Labels: enhancement, ccs

#1625 (role/rke2*) disable rke2-snapshot-controller related helm charts
  hieradata/common.yaml
  spec/hosts/roles/rke2agent_spec.rb
  spec/hosts/roles/rke2server_spec.rb
Labels: bug

#1623 (manke/konkong) RKE2 Migration
  hieradata/cluster/konkong.yaml
  hieradata/cluster/konkong/role/rke2agent.yaml
  hieradata/cluster/konkong/role/rke2server.yaml
  hieradata/cluster/manke.yaml
  hieradata/cluster/manke/role/rke2agent.yaml
  hieradata/cluster/manke/role/rke2server.yaml
  konkong.eyaml
  spec/hosts/nodes/konkong01.ls.lsst.org_spec.rb
  spec/hosts/nodes/manke01.ls.lsst.org_spec.rb
Labels: enhancement

#1643 (Puppetfile) switch clustershell back to upstream version
  Puppetfile
Labels: enhancement

#1645 (cluster/{auxtel,lsstcam}-ccs) add ccs release 39.2.3
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs

#1646 (cluster/comcam-ccs) add ccs release 39.2.3
  hieradata/cluster/comcam-ccs.yaml
Labels: enhancement, ccs

#1642 (node/lsstcam-{fcs,quad,rebps,vac}) set ccs_hcu quadbox flag
  Puppetfile
  hieradata/node/lsstcam-fcs.cp.lsst.org.yaml
  hieradata/node/lsstcam-quad.cp.lsst.org.yaml
  hieradata/node/lsstcam-rebps.cp.lsst.org.yaml
  hieradata/node/lsstcam-vac.cp.lsst.org.yaml
  spec/hosts/nodes/lsstcam-fcs.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-quad.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-rebps.cp.lsst.org_spec.rb
  spec/hosts/nodes/lsstcam-vac.cp.lsst.org_spec.rb
Labels: enhancement, ccs

#1626 (cluster/yagan) convert from rke1 -> rke2
  hieradata/cluster/amor/osfamily/RedHat/major/7.yaml
  hieradata/cluster/yagan.yaml
  hieradata/cluster/yagan/role/rke2agent.yaml
  hieradata/cluster/yagan/role/rke2server.yaml
  hieradata/cluster/yagan/variant/1114s.yaml
  hieradata/cluster/yagan/variant/1114s/subvariant/1.01.yaml
  hieradata/cluster/yagan/variant/1114s/subvariant/1.02.yaml
  hieradata/common.yaml
  hieradata/node/foreman.cp.lsst.org.yaml
  hieradata/node/nfs1.cp.lsst.org.yaml
  hieradata/node/nfs3.cp.lsst.org.yaml
  hieradata/node/yagan18.cp.lsst.org.yaml
  hieradata/node/yagan19.cp.lsst.org.yaml
  hieradata/node/yagan20.cp.lsst.org.yaml
  spec/hosts/nodes/elqui01.cp.lsst.org_spec.rb
  spec/hosts/nodes/foreman.cp.lsst.org_spec.rb
  spec/hosts/nodes/nfs1.cp.lsst.org_spec.rb
  spec/hosts/nodes/nfs3.cp.lsst.org_spec.rb
  spec/hosts/nodes/pillan01.tu.lsst.org_spec.rb
  spec/hosts/nodes/pillan08.tu.lsst.org_spec.rb
  spec/hosts/nodes/yagan01.cp.lsst.org_spec.rb
  spec/hosts/nodes/yagan11.cp.lsst.org_spec.rb
  spec/spec_helper.rb
  spec/support/spec/ipset.rb
Labels: enhancement

#1647 (node/nfs[13].cp) allow nfs mounts from vlan1800
  hieradata/node/nfs1.cp.lsst.org.yaml
  hieradata/node/nfs3.cp.lsst.org.yaml
  spec/hosts/nodes/nfs1.cp.lsst.org_spec.rb
  spec/hosts/nodes/nfs3.cp.lsst.org_spec.rb
Labels: enhancement

#1648 (manke|yagan) add missing local-storage: "true" node labels
  hieradata/node/manke08.cp.lsst.org.yaml
  hieradata/node/manke09.cp.lsst.org.yaml
  hieradata/node/manke10.cp.lsst.org.yaml
  hieradata/node/yagan17.cp.lsst.org.yaml
Labels: bug

#1644 (host/tel-hw1.ls) add scratch mount
  hieradata/node/tel-hw1.ls.lsst.org.yaml
  spec/hosts/nodes/tel-hw1.ls.lsst.org_spec.rb
Labels: enhancement

#1650 (node/auxtel-ill-control.cp) add missing nfs mount
  hieradata/node/auxtel-ill-control.cp.lsst.org.yaml
  hieradata/role/fiberspec.yaml
  spec/hosts/nodes/auxtel-ill-control.cp.lsst.org_spec.rb
Labels: enhancement

#1651 (cluster/{auxtel,comcam,lsstcam}-ccs) add new ccs release 40.0.0
  hieradata/cluster/auxtel-ccs.yaml
  hieradata/cluster/comcam-ccs.yaml
  hieradata/cluster/lsstcam-ccs.yaml
Labels: enhancement, ccs
